using System;
using System.Linq;
using PincabToolbox.Core.Models;
using PincabToolbox.Repair;

namespace PincabToolbox.App.Localization;

/// <summary>
/// Minimal trilingual string table (EN/FR/ES). 14/08/2026, decision Maxime: English-speaking
/// pinball cabinet builders are the larger audience, so the app now always opens in English on a
/// fresh install, regardless of OS culture — no more guessing a French cab from a French Windows.
/// A returning user's own choice (<see cref="SetLang"/>, restored from settings at startup) still
/// wins over this default; only the very first launch is affected.
/// </summary>
public static class Loc
{
    private static readonly string[] SupportedLangs = { "en", "fr", "es" };

    public static string Lang { get; private set; } = "en";

    public static event Action? LanguageChanged;

    /// <summary>
    /// Force a specific language ("en"/"fr"/"es"). Used to restore the saved preference at
    /// startup, and — since 14/08/2026 (bis) — by each of the 3 always-visible language buttons
    /// (MainWindow's BtnLangEn/Fr/Es), which replaced the earlier single cycling toggle button
    /// (Maxime: a one-button EN→FR→ES→EN cycle wasn't discoverable — a user who didn't already
    /// know the other languages existed had no way to find them). Anything unrecognised degrades
    /// to English.
    /// </summary>
    public static void SetLang(string lang)
    {
        lang = SupportedLangs.Contains(lang) ? lang : "en";
        if (lang == Lang) return;
        Lang = lang;
        LanguageChanged?.Invoke();
    }

    public static string Get(string key)
    {
        if (Lang == "fr" && Fr.TryGetValue(key, out var fr)) return fr;
        if (Lang == "es" && Es.TryGetValue(key, out var es)) return es;
        return En.TryGetValue(key, out var en) ? en : key;
    }

    /// <summary>Localized finding text — falls back to the Core's English rendering.</summary>
    public static string FindingText(Finding f)
    {
        var table = Lang switch { "fr" => FrFindings, "es" => EsFindings, _ => null };
        if (table is null || !table.TryGetValue(f.Code, out var template)) return f.EnglishText;
        try
        {
            return string.Format(template, f.Args.Cast<object?>().ToArray());
        }
        catch (FormatException)
        {
            return f.EnglishText;
        }
    }

    /// <summary>Localized fix hint by finding code; falls back to the Core's English FixHint.</summary>
    public static string? FixHintText(Finding f)
    {
        if (f.FixHint is null) return null;
        var table = Lang switch { "fr" => FrFixHints, "es" => EsFixHints, _ => null };
        if (table is not null && table.TryGetValue(f.Code, out var localized)) return localized;
        return f.FixHint;
    }

    /// <summary>
    /// Localized text for a <see cref="RepairLimitation"/> (13/08/2026 fix — the ADR-006
    /// "not automatable" line and the manual-item confirmation text were both showing raw English
    /// in the FR UI; extended 14/08 for ES). Priority: the reason's own localized text (scenario
    /// steps carry one from the pack), then this table's fix-hint keyed by the same code (findings
    /// without a pack rule, e.g. ROM_MISSING), then the English fallback — never a blank line.
    /// </summary>
    public static string MissingReasonText(RepairLimitation m)
    {
        if (Lang == "fr")
        {
            if (!string.IsNullOrWhiteSpace(m.MessageFr)) return m.MessageFr;
            if (m.Code is not null && FrFixHints.TryGetValue(m.Code, out var fr)) return fr;
        }
        else if (Lang == "es")
        {
            if (!string.IsNullOrWhiteSpace(m.MessageEs)) return m.MessageEs;
            if (m.Code is not null && EsFixHints.TryGetValue(m.Code, out var es)) return es;
        }
        return m.MessageEn;
    }

    public static string SeverityLabel(Severity s) => Get("sev." + s);

    private static readonly Dictionary<string, string> En = new()
    {
        ["app.title"] = "Pincab Toolbox",
        ["tab.scanner"] = "Scanner",
        ["tab.diff"] = "Script Diff",
        ["tab.about"] = "About",
        ["tab.repair"] = "Repair",
        ["scan.root"] = "Pincab root folder:",
        ["scan.browse"] = "Browse…",
        ["scan.demo"] = "Demo mode",
        ["scan.start"] = "SCAN MY PINCAB",
        ["scan.running"] = "Scanning…",
        ["scan.cancel"] = "Cancel",
        ["scan.export"] = "Export report",
        ["scan.copyforum"] = "Copy for forum",
        ["report.copied"] = "Report copied to clipboard — paste it on the forum.",
        ["scan.placeholder"] = "Select the root folder of your virtual pinball installation (the one that contains Tables, VPinMAME, PinUPSystem…) and press Scan.",
        ["scan.empty"] = "No findings yet.",
        ["scan.hint.notables"] = "No .vpx tables found — check that you selected the right folder.",
        ["filter.critical"] = "Critical",
        ["filter.warning"] = "Warnings",
        ["filter.note"] = "Notes",
        ["filter.info"] = "Info",
        ["filter.ok"] = "OK",
        ["score.a"] = "Healthy install",
        ["score.b"] = "A few things to watch",
        ["score.c"] = "Needs fixing",
        ["score.f"] = "Install in bad shape",
        // Bandeau du Scanner (maquette 11/08) — dit le nombre de bloquants plutôt que la seule note.
        ["diagnosis.conf.high"] = "high",
        ["diagnosis.conf.mid"] = "medium",
        ["diagnosis.conf.low"] = "low",
        ["hero.ok"] = "No blocking problem found",
        ["hero.blocking.one"] = "1 blocking problem is stopping a table from starting",
        ["hero.blocking.many"] = "{0} blocking problems are stopping tables from starting",
        ["priority.label"] = "FIX THIS FIRST",
        ["priority.watch"] = "WORTH A LOOK",
        ["diagnosis.label"] = "MAIN DIAGNOSIS",
        ["diagnosis.confidence"] = "reliability",
        ["priority.basedon"] = "Based on:",
        ["detail.impact"] = "IMPACT",
        ["detail.cause"] = "PROBABLE CAUSE",
        ["detail.fix"] = "RECOMMENDED FIX",
        ["detail.symptom"] = "WHAT YOU'LL NOTICE",
        ["detail.explanation"] = "GOOD TO KNOW",
        ["detail.verify"] = "HOW TO VERIFY",
        // Écran 1 (UX-COPY-Repair.md) — facts computed from the real plan by RepairOfferBuilder,
        // never declared.
        ["repair.checks.fixable"] = "✓ Fixable automatically",
        ["repair.checks.backup"] = "✓ Backed up before changing",
        ["repair.checks.reversible"] = "✓ Reversible — one click to undo",
        ["repair.checks.duration.seconds"] = "⏱ A few seconds",
        ["repair.checks.duration.underminute"] = "⏱ Under a minute",
        ["repair.checks.duration.minutes"] = "⏱ A few minutes",
        ["repair.tag"] = "→ See the Repair tab to apply this fix",
        ["repair.summary"] = "Repair could fix {0} of the {1} findings here automatically — see the Repair tab.",
        ["repair.notautomatable"] = "Some steps will always stay manual, licence or not:",
        ["repair.goto"] = "Go to the Repair tab →",

        // Écran 2 (LOT H, spec 10/08) — the write path itself.
        ["repair.intro"] = "Repair can fix some of the findings above automatically: every change is backed up first and can be undone, and nothing is ever applied without your explicit, per-item confirmation. Enter your license key, build the plan, review it, then choose what to apply.",
        ["repair.license.label"] = "License key",
        ["repair.license.hint"] = "Paste the key you received after purchase.",
        ["repair.license.verify"] = "Verify",
        ["repair.license.valid"] = "✓ Valid license.",
        ["repair.license.invalid"] = "Invalid or missing license key — Repair will only show what could be fixed, not apply it.",
        ["repair.forceddryrun.banner"] = "⚠ SIMULATION MODE — PINCAB_REPAIR_FORCE_DRYRUN is set. Apply will report what it would have done, but will change nothing on disk.",
        ["repair.forceddryrun.applied"] = "Simulation only — nothing was written to disk.",
        ["repair.plan.build"] = "Analyze what can be repaired",
        ["repair.plan.status"] = "{0} fixable item(s), {1} manual step(s) to do yourself. Review the list below.",
        ["repair.plan.empty"] = "Nothing to apply right now — either everything is already fine, every fix needs a license, or the remaining steps stay manual.",
        ["repair.needscan"] = "Run a scan first, from the Scanner tab.",
        ["repair.noneselected"] = "Nothing selected — check at least one item before applying.",
        ["repair.manual.label"] = "Manual — Repair cannot fix this automatically",
        ["repair.manual.noreason"] = "No automated fix exists for this yet — see the finding's own guidance in the Scanner report.",
        ["repair.locked.label"] = "A fix exists — a valid license is needed to see and apply it.",
        ["repair.reversible.yes"] = "Reversible",
        ["repair.reversible.no"] = "Cannot be undone",
        ["repair.backup.yes"] = "Backed up first",
        ["repair.backup.no"] = "No backup (nothing to restore)",
        ["repair.confirm.title"] = "This cannot be undone",
        ["repair.confirm.nonreversible"] = "At least one selected fix cannot be undone once applied. Do you want to continue?",
        ["repair.apply.button"] = "Apply selected fixes",
        ["repair.apply.running"] = "Applying…",
        ["repair.apply.status"] = "{0} applied, {1} failed.",
        ["repair.apply.recovery"] = "Something went wrong while undoing a partial change — a backup is kept here, restore it by hand if needed:",
        ["repair.done.label"] = "Repaired",
        ["repair.done.empty"] = "No fix applied yet.",
        ["repair.done.count"] = "{0} — {1} fix(es) applied",
        ["repair.done.partiallyundone"] = "{0} of them already undone — the rest is still standing.",
        ["repair.done.fullyundone"] = "Fully undone.",
        ["repair.undone.label"] = "Undone",
        ["repair.undone.empty"] = "No plan undone yet.",
        ["repair.undo.button"] = "Undo",
        ["repair.undo.ok"] = "Undone.",
        ["repair.undo.fail"] = "Could not fully undo:",
        ["repair.undo.journalwarning"] = "⚠ The last write to the undo journal failed — Undo may be incomplete for the most recent action.",
        ["col.severity"] = "Severity",
        ["col.category"] = "Module",
        ["col.subject"] = "Subject",
        ["col.message"] = "Details",
        ["col.action"] = "Action",
        ["search.hint"] = "Search…",
        ["action.folder"] = "Open folder",
        ["action.update"] = "Open update",
        ["action.copy"] = "Copy details",
        ["action.copied"] = "Copied to clipboard.",
        ["sev.Critical"] = "CRITICAL",
        ["sev.Warning"] = "Warning",
        ["sev.Note"] = "Note",
        ["sev.Info"] = "Info",
        ["sev.Ok"] = "OK",
        ["diff.old"] = "Old table (.vpx or .vbs):",
        ["diff.new"] = "New table (.vpx or .vbs):",
        ["diff.compare"] = "Compare scripts",
        ["diff.summary"] = "{0} modified · {1} added · {2} removed",
        ["diff.placeholder"] = "Pick two versions of a table (or two .vbs scripts) to see exactly what changed — before installing an update blindly.",
        ["report.saved"] = "Report saved: ",
        ["status.ready"] = "Ready.",
        ["status.done"] = "Analysis complete · {0} checks — {1} critical, {2} warnings, {3} info, {4} notes.",
        ["scan.demolabel"] = "Demo — sample install",
        ["diff.empty"] = "Compare the script of two versions of a table (.vpx or .vbs) to see exactly what changed. Pick an old and a new file above, then Compare.",
        ["scan.copied"] = "✓ Copied",
        ["cat.rom"] = "ROM",
        ["cat.bitness"] = "32/64-bit",
        ["cat.completeness"] = "Install",
        ["cat.compat"] = "Compatibility",
        ["cat.updates"] = "Updates",
        ["cat.security"] = "Security",
        ["cat.dependencies"] = "Plugins",
        ["cat.aliasloop"] = "VPMAlias",
        ["cat.nvram"] = "NVRAM",
        ["cat.altcolor"] = "AltColor",
        ["cat.altsound"] = "AltSound",
        ["cat.screentopology"] = "Screen Topology",
        ["cat.junctions"] = "Junctions",
        ["cat.directb2s"] = "DirectB2S",
        ["cat.popperplaylist"] = "Playlists",
        ["cat.legacy"] = "Legacy Tables",
        ["cat.disk"] = "Disk Space",
        ["cat.process"] = "PinUP Display",
        ["cat.display"] = "Display Setup",
        ["cat.media-orphan"] = "Orphaned Media",
        ["cat.vpxversion"] = "VPX Version",
        // Lot communauté 10/08 (LOT A→G).
        ["cat.com"] = "COM Registration",
        ["cat.chain-bitness"] = "Chain Bitness",
        ["cat.dmd-config"] = "DMD Config",
        ["cat.feature-enabled"] = "Feature Enabled",
        ["cat.screenres-format"] = "ScreenRes Format",
        ["cat.nvram-writable"] = "NVRAM Writability",
        // Tier B (handoff Sonnet 5, 06/08) — ces 5 scanners n'avaient jamais eu de libellé : la
        // colonne Module affichait la clé brute « cat.dpi-scaling ». Tous émettent en Severity.Note,
        // donc l'encadré Remarques de l'écran porté les montre maintenant aussi. Corrigé ici.
        ["cat.audio-state"] = "Audio",
        ["cat.config-phantom"] = "Duplicate Config",
        ["cat.dmd-com-port"] = "DMD COM Port",
        ["cat.dpi-scaling"] = "DPI Scaling",
        ["cat.locale-separator"] = "Decimal Separator",
        ["about.tagline"] = "The mechanic for your pincab.",
        ["about.body"] = "Pincab Toolbox scans your Visual Pinball X / PinUP Popper installation and tells you what is broken, missing or mismatched — before you hit Start on a table.\n\n• 100% local scanning — your cab, your files and your findings are never uploaded, no telemetry, no account.\n• Read-only — the free scanner never modifies a single file.\n• The Update Watcher uses the open-source Virtual Pinball Spreadsheet database and only ever links you to official pages. It never downloads tables, ROMs or media.\n• The one exception: the \"Check for updates\" button below is manual and opt-in — click it, and it contacts GitHub just to see if a newer version exists. Nothing about your cab, your tables or your scan results is ever sent. It never runs on its own.",
        ["about.version"] = "Version",
        ["about.checkupdate"] = "Check for updates",
        ["about.update.checking"] = "Checking…",
        ["about.update.uptodate"] = "You're up to date ({0}).",
        ["about.update.available"] = "New version {0} available — click to open the release page.",
        ["about.update.error"] = "Couldn't check for updates (offline, or GitHub unreachable). Try again later.",
        ["onb.title"] = "Welcome to Pincab Toolbox",
        ["onb.lead"] = "A quick health check for your virtual pinball cabinet. About one minute, and completely safe.",
        ["onb.p1"] = "✓  Read-only — it never modifies a single file.",
        ["onb.p2"] = "✓  100% local — nothing is uploaded, no account, no telemetry.",
        ["onb.p3"] = "✓  It finds what's broken, missing or mismatched — and explains how to fix it.",
        ["onb.start"] = "Let's go",
        // ── Écran Scanner porté sur la maquette 11/08 (docs/maquette-scanner-2026-08-11.html) ──
        // Sous-titre du bandeau : nombre de causes de fond réellement détectées (Scenarios.DetectAll).
        // Pas de promesse "tout se règle en cascade" — seule la relation cause→symptômes est affirmée.
        ["hero.causes.one"] = "The findings come down to 1 root cause — fix the cause, not each symptom one by one.",
        ["hero.causes.many"] = "The findings come down to {0} root causes — fix the causes, not each symptom one by one.",
        // Ligne méta sous le bandeau — chaque valeur vient du vrai scan (ScanReport / ScanEngine).
        ["meta.mode"] = "Mode",
        ["meta.mode.demo"] = "Demonstration",
        ["meta.mode.folder"] = "Folder",
        ["meta.started"] = "Started",
        ["meta.duration"] = "Duration",
        ["meta.checks"] = "Checks",
        ["meta.tablecount"] = "Tables analyzed",
        // Onglets internes du Scanner.
        ["stab.causes"] = "Root causes",
        ["stab.results"] = "All findings",
        ["stab.components"] = "Components",
        ["stab.tables"] = "Tables",
        ["stab.system"] = "System",
        // Cartes de causes racines.
        ["card.conf"] = "Confidence",
        ["card.comp.one"] = "{0} component",
        ["card.comp.many"] = "{0} components",
        ["card.tbl.one"] = "{0} table of {1}",
        ["card.tbl.many"] = "{0} tables of {1}",
        ["card.manual"] = "⚑ Manual fix",
        ["card.steps"] = "See the steps →",
        // Colonne de droite.
        ["side.criticals"] = "CRITICAL FINDINGS",
        ["side.components"] = "COMPONENT HEALTH",
        ["side.notes"] = "NOTES",
        ["side.comp.note"] = "A component no table uses is never counted as a problem. Nothing is inferred from a failed read: in that case Pincab Toolbox stays silent.",
        // Santé des composants — noms d'affichage par rôle du profil, statuts par code réel.
        ["comp.name.main-exe"] = "Visual Pinball X",
        ["comp.name.vpinmame"] = "VPinMAME",
        ["comp.name.vpinmame64"] = "VPinMAME 64-bit",
        ["comp.name.dmddevice"] = "dmddevice",
        ["comp.name.dmddevice64"] = "dmddevice 64-bit",
        ["comp.name.b2s"] = "B2S Backglass Server",
        ["comp.name.flexdmd"] = "FlexDMD",
        ["comp.name.popper"] = "PinUP Popper",
        ["comp.meta.absent"] = "missing",
        ["comp.meta.dbread"] = "database read",
        ["comp.meta.dbunreadable"] = "database unreadable",
        ["comp.st.ok"] = "✓ OK",
        ["comp.st.critical"] = "✕ Critical",
        ["comp.st.warn"] = "▲ Warning",
        ["comp.st.note"] = "✎ Note",
        ["comp.code.BITNESS_DMD64_MISSING"] = "▲ 64-bit missing",
        ["comp.code.B2S_SERVER_MISSING"] = "▲ Missing",
        ["comp.code.FLEXDMD_MISSING"] = "▲ Missing",
        ["comp.code.VPINMAME_NOT_REGISTERED"] = "✕ Not registered",
        // Tableau des tables analysées — chaque cellule vient d'un résultat de scan ou d'une
        // lecture positive (base Popper via SqliteReader) ; "—" = non vérifié sur ce scan.
        ["tbl.header"] = "TABLES ANALYZED",
        ["tbl.h.table"] = "Table",
        ["tbl.h.rom"] = "ROM",
        ["tbl.h.b2s"] = "Backglass",
        ["tbl.h.frontend"] = "Frontend",
        ["tbl.rom.ok"] = "✓ {0}",
        ["tbl.rom.missing"] = "✕ {0} missing",
        ["tbl.rom.notrequired"] = "✓ none required",
        ["tbl.rom.unzipped"] = "▲ unzipped",
        ["tbl.b2s.present"] = "✓ present",
        ["tbl.b2s.missing"] = "missing",
        ["tbl.fe.registered"] = "✓ registered",
        ["tbl.fe.notregistered"] = "not registered",
        ["tbl.unknown"] = "—",
        // Carte réparation (état honnête — ADR-006).
        ["repaircard.none.title"] = "No automatic repair available on this scan",
        ["repaircard.none.body"] = "Repair can fix 4 kinds of problems today (file blocked by Windows, unzipped ROM, orphaned media, stuck display process). None is present here: the causes above require installing or registering a component, which a tool should never do for you without you seeing exactly what.",
        ["repaircard.some.title"] = "Automatic repair available",
        ["repaircard.open"] = "Open Repair",
        // Onglet Système — uniquement des faits mesurés (scan + machine), jamais de valeur déduite.
        ["sys.needscan"] = "Run a scan to fill this tab.",
        ["sys.scan.header"] = "LAST SCAN",
        ["sys.machine.header"] = "MACHINE",
        ["sys.root"] = "Scanned root",
        ["sys.dirs"] = "Resolved folders",
        ["sys.os"] = "System",
        ["sys.cpu"] = "Processor",
        ["sys.cores"] = "{0} logical cores",
        ["sys.ram"] = "Memory",
        ["sys.ram.fmt"] = "{0} GB available",
        ["sys.screens"] = "Screens",
        ["sys.screens.fmt"] = "{0} screen(s) — virtual desktop {1} × {2}",
        // Renvois des listes plafonnées (le total réel reste affiché dans l'en-tête du bloc).
        ["more.tables"] = "+{0} more — Tables tab",
        ["more.results"] = "+{0} more — All findings tab",
    };

    private static readonly Dictionary<string, string> Fr = new()
    {
        ["app.title"] = "Pincab Toolbox",
        ["tab.scanner"] = "Scanner",
        ["tab.diff"] = "Diff de scripts",
        ["tab.about"] = "À propos",
        ["tab.repair"] = "Repair",
        ["scan.root"] = "Dossier racine du pincab :",
        ["scan.browse"] = "Parcourir…",
        ["scan.demo"] = "Mode démo",
        ["scan.start"] = "SCANNER MON PINCAB",
        ["scan.running"] = "Scan en cours…",
        ["scan.cancel"] = "Annuler",
        ["scan.export"] = "Exporter le rapport",
        ["scan.copyforum"] = "Copier pour le forum",
        ["report.copied"] = "Rapport copié — colle-le sur le forum.",
        ["scan.placeholder"] = "Sélectionne le dossier racine de ton installation (celui qui contient Tables, VPinMAME, PinUPSystem…) puis lance le scan.",
        ["scan.empty"] = "Aucun résultat pour l'instant.",
        ["scan.hint.notables"] = "Aucune table .vpx trouvée — vérifie que tu as choisi le bon dossier.",
        ["filter.critical"] = "Critiques",
        ["filter.warning"] = "Avertissements",
        ["filter.note"] = "Notes",
        ["filter.info"] = "Infos",
        ["filter.ok"] = "OK",
        ["score.a"] = "Installation saine",
        ["score.b"] = "Quelques points à surveiller",
        ["score.c"] = "Installation à corriger",
        ["score.f"] = "Installation en mauvais état",
        // Bandeau du Scanner (maquette 11/08) — dit le nombre de bloquants plutôt que la seule note.
        ["diagnosis.conf.high"] = "élevée",
        ["diagnosis.conf.mid"] = "moyenne",
        ["diagnosis.conf.low"] = "faible",
        ["hero.ok"] = "Aucun problème bloquant détecté",
        ["hero.blocking.one"] = "1 problème bloquant empêche une table de démarrer",
        ["hero.blocking.many"] = "{0} problèmes bloquants empêchent des tables de démarrer",
        ["priority.label"] = "À CORRIGER EN PRIORITÉ",
        ["priority.watch"] = "À VÉRIFIER",
        ["diagnosis.label"] = "DIAGNOSTIC PRINCIPAL",
        ["diagnosis.confidence"] = "fiabilité",
        ["priority.basedon"] = "Basé sur :",
        ["detail.impact"] = "IMPACT",
        ["detail.cause"] = "CAUSE PROBABLE",
        ["detail.fix"] = "CORRECTIF RECOMMANDÉ",
        ["detail.symptom"] = "CE QUE VOUS REMARQUEREZ",
        ["detail.explanation"] = "BON À SAVOIR",
        ["detail.verify"] = "COMMENT VÉRIFIER",
        // Écran 1 (UX-COPY-Repair.md) — faits calculés depuis le plan réel par RepairOfferBuilder,
        // jamais déclarés.
        ["repair.checks.fixable"] = "✓ Réparable automatiquement",
        ["repair.checks.backup"] = "✓ Sauvegarde avant modification",
        ["repair.checks.reversible"] = "✓ Réversible — annulable en un clic",
        ["repair.checks.duration.seconds"] = "⏱ Quelques secondes",
        ["repair.checks.duration.underminute"] = "⏱ Moins d'une minute",
        ["repair.checks.duration.minutes"] = "⏱ Quelques minutes",
        ["repair.tag"] = "→ Voir l'onglet Repair pour appliquer ce correctif",
        ["repair.summary"] = "Repair pourrait corriger {0} problème(s) sur {1} détecté(s) automatiquement — voir l'onglet Repair.",
        ["repair.notautomatable"] = "Certaines étapes resteront toujours manuelles, licence ou pas :",
        ["repair.goto"] = "Aller à l'onglet Repair →",

        // Écran 2 (LOT H, spec 10/08) — le chemin d'écriture lui-même.
        ["repair.intro"] = "Repair peut corriger automatiquement certains résultats ci-dessus : chaque modification est sauvegardée avant d'être appliquée et peut être annulée, et rien n'est jamais appliqué sans ta confirmation explicite, poste par poste. Entre ta clé de licence, construis le plan, vérifie-le, puis choisis ce que tu veux appliquer.",
        ["repair.license.label"] = "Clé de licence",
        ["repair.license.hint"] = "Colle la clé reçue après ton achat.",
        ["repair.license.verify"] = "Vérifier",
        ["repair.license.valid"] = "✓ Licence valide.",
        ["repair.license.invalid"] = "Clé de licence absente ou invalide, Repair affichera seulement ce qui pourrait être corrigé, sans l'appliquer.",
        ["repair.forceddryrun.banner"] = "⚠ MODE SIMULATION — PINCAB_REPAIR_FORCE_DRYRUN est actif. Apply annoncera ce qu'il aurait fait, mais rien ne sera écrit sur le disque.",
        ["repair.forceddryrun.applied"] = "Simulation uniquement, rien n'a été écrit sur le disque.",
        ["repair.plan.build"] = "Analyser ce qui peut être réparé",
        ["repair.plan.status"] = "{0} correctif(s) automatique(s), {1} étape(s) manuelle(s) à faire toi-même. Vérifie la liste ci-dessous.",
        ["repair.plan.empty"] = "Rien à appliquer pour l'instant, soit tout va déjà bien, soit chaque correctif nécessite une licence, soit les étapes restantes restent manuelles.",
        ["repair.needscan"] = "Lance d'abord un scan depuis l'onglet Scanner.",
        ["repair.noneselected"] = "Rien n'est sélectionné, coche au moins un élément avant d'appliquer.",
        ["repair.manual.label"] = "Manuel — Repair ne peut pas corriger ça automatiquement",
        ["repair.manual.noreason"] = "Aucun correctif automatique n'existe encore pour ça, voir l'indication de ce résultat dans le rapport Scanner.",
        ["repair.locked.label"] = "Un correctif existe, une licence valide est nécessaire pour le voir et l'appliquer.",
        ["repair.reversible.yes"] = "Réversible",
        ["repair.reversible.no"] = "Non annulable",
        ["repair.backup.yes"] = "Sauvegardé avant modification",
        ["repair.backup.no"] = "Pas de sauvegarde (rien à restaurer)",
        ["repair.confirm.title"] = "Cette action est irréversible",
        ["repair.confirm.nonreversible"] = "Au moins un correctif sélectionné ne pourra pas être annulé une fois appliqué. Veux-tu continuer ?",
        ["repair.apply.button"] = "Appliquer les correctifs sélectionnés",
        ["repair.apply.running"] = "Application en cours…",
        ["repair.apply.status"] = "{0} appliqué(s), {1} échoué(s).",
        ["repair.apply.recovery"] = "Un problème est survenu en annulant une modification partielle, une sauvegarde est conservée ici, restaure-la à la main si besoin :",
        ["repair.done.label"] = "Réparé",
        ["repair.done.empty"] = "Aucun correctif appliqué pour l'instant.",
        ["repair.done.count"] = "{0} — {1} correctif(s) appliqué(s)",
        ["repair.done.partiallyundone"] = "{0} déjà annulé(s) — le reste tient toujours.",
        ["repair.done.fullyundone"] = "Entièrement annulé.",
        ["repair.undone.label"] = "Annulé",
        ["repair.undone.empty"] = "Aucun plan annulé.",
        ["repair.undo.button"] = "Annuler",
        ["repair.undo.ok"] = "Annulé.",
        ["repair.undo.fail"] = "Annulation incomplète :",
        ["repair.undo.journalwarning"] = "⚠ La dernière écriture du journal d'annulation a échoué, Undo pourrait être incomplet pour l'action la plus récente.",
        ["col.severity"] = "Gravité",
        ["col.category"] = "Module",
        ["col.subject"] = "Sujet",
        ["col.message"] = "Détails",
        ["col.action"] = "Action",
        ["search.hint"] = "Rechercher…",
        ["action.folder"] = "Ouvrir le dossier",
        ["action.update"] = "Voir la mise à jour",
        ["action.copy"] = "Copier les détails",
        ["action.copied"] = "Copié dans le presse-papiers.",
        ["sev.Critical"] = "CRITIQUE",
        ["sev.Warning"] = "Avertissement",
        ["sev.Note"] = "À noter",
        ["sev.Info"] = "Info",
        ["sev.Ok"] = "OK",
        ["diff.old"] = "Ancienne table (.vpx ou .vbs) :",
        ["diff.new"] = "Nouvelle table (.vpx ou .vbs) :",
        ["diff.compare"] = "Comparer les scripts",
        ["diff.summary"] = "{0} modifiées · {1} ajoutées · {2} supprimées",
        ["diff.placeholder"] = "Choisis deux versions d'une table (ou deux scripts .vbs) pour voir exactement ce qui a changé — avant d'installer une mise à jour à l'aveugle.",
        ["report.saved"] = "Rapport enregistré : ",
        ["status.ready"] = "Prêt.",
        ["status.done"] = "Analyse terminée · {0} vérifications — {1} critiques, {2} avertissements, {3} infos, {4} à noter.",
        ["scan.demolabel"] = "Démo — installation d'exemple",
        ["diff.empty"] = "Compare le script de deux versions d'une table (.vpx ou .vbs) pour voir exactement ce qui a changé. Choisis un ancien et un nouveau fichier ci-dessus, puis Comparer.",
        ["scan.copied"] = "✓ Copié",
        ["cat.rom"] = "ROM",
        ["cat.bitness"] = "32/64-bit",
        ["cat.completeness"] = "Install",
        ["cat.compat"] = "Compatibilité",
        ["cat.updates"] = "Mises à jour",
        ["cat.security"] = "Sécurité",
        ["cat.dependencies"] = "Plugins",
        ["cat.aliasloop"] = "VPMAlias",
        ["cat.nvram"] = "NVRAM",
        ["cat.altcolor"] = "AltColor",
        ["cat.altsound"] = "AltSound",
        ["cat.screentopology"] = "Topologie écrans",
        ["cat.junctions"] = "Jonctions",
        ["cat.directb2s"] = "DirectB2S",
        ["cat.popperplaylist"] = "Playlists",
        ["cat.legacy"] = "Tables anciennes",
        ["cat.disk"] = "Espace disque",
        ["cat.process"] = "PinUP Display",
        ["cat.display"] = "Configuration écrans",
        ["cat.media-orphan"] = "Médias orphelins",
        ["cat.vpxversion"] = "Version VPX",
        // Lot communauté 10/08 (LOT A→G).
        ["cat.com"] = "Enregistrement COM",
        ["cat.chain-bitness"] = "Chaîne 32/64-bit",
        ["cat.dmd-config"] = "Config DMD",
        ["cat.feature-enabled"] = "Fonction activée",
        ["cat.screenres-format"] = "Format ScreenRes",
        ["cat.nvram-writable"] = "Écriture NVRAM",
        ["cat.audio-state"] = "Audio",
        ["cat.config-phantom"] = "Config en double",
        ["cat.dmd-com-port"] = "Port COM du DMD",
        ["cat.dpi-scaling"] = "Mise à l'échelle",
        ["cat.locale-separator"] = "Séparateur décimal",
        ["about.tagline"] = "Le mécanicien de ton pincab.",
        ["about.body"] = "Pincab Toolbox scanne ton installation Visual Pinball X / PinUP Popper et te dit ce qui est cassé, manquant ou incompatible — avant que tu ne lances une table.\n\n• Scan 100 % local — ta cab, tes fichiers et tes résultats de scan ne sont jamais envoyés, zéro télémétrie, zéro compte.\n• Lecture seule — le scanner gratuit ne modifie jamais le moindre fichier.\n• L'Update Watcher s'appuie sur la base open source Virtual Pinball Spreadsheet et se contente de te donner le lien officiel. Il ne télécharge jamais ni table, ni ROM, ni média.\n• Seule exception : le bouton « Vérifier les mises à jour » ci-dessous est manuel et volontaire — tu cliques, et il contacte GitHub juste pour voir si une nouvelle version existe. Rien concernant ta cab, tes tables ou tes résultats de scan n'est jamais envoyé. Il ne se déclenche jamais tout seul.",
        ["about.version"] = "Version",
        ["about.checkupdate"] = "Vérifier les mises à jour",
        ["about.update.checking"] = "Vérification…",
        ["about.update.uptodate"] = "Tu es à jour ({0}).",
        ["about.update.available"] = "Nouvelle version {0} disponible — clique pour ouvrir la page de la release.",
        ["about.update.error"] = "Impossible de vérifier (hors ligne, ou GitHub inaccessible). Réessaie plus tard.",
        ["onb.title"] = "Bienvenue dans Pincab Toolbox",
        ["onb.lead"] = "Un diagnostic rapide de ton flipper virtuel. Environ une minute, et totalement sans risque.",
        ["onb.p1"] = "✓  Lecture seule — ne modifie jamais le moindre fichier.",
        ["onb.p2"] = "✓  100 % local — rien n'est envoyé, sans compte, sans télémétrie.",
        ["onb.p3"] = "✓  Il trouve ce qui est cassé, manquant ou incompatible — et explique comment corriger.",
        ["onb.start"] = "C'est parti",
        // ── Écran Scanner porté sur la maquette 11/08 (docs/maquette-scanner-2026-08-11.html) ──
        ["hero.causes.one"] = "Les résultats se ramènent à 1 cause de fond — corrige la cause plutôt que chaque symptôme un par un.",
        ["hero.causes.many"] = "Les résultats se ramènent à {0} causes de fond — corrige les causes plutôt que chaque symptôme un par un.",
        ["meta.mode"] = "Mode",
        ["meta.mode.demo"] = "Démonstration",
        ["meta.mode.folder"] = "Dossier",
        ["meta.started"] = "Lancé le",
        ["meta.duration"] = "Durée",
        ["meta.checks"] = "Contrôles",
        ["meta.tablecount"] = "Tables analysées",
        ["stab.causes"] = "Causes racines",
        ["stab.results"] = "Tous les résultats",
        ["stab.components"] = "Composants",
        ["stab.tables"] = "Tables",
        ["stab.system"] = "Système",
        ["card.conf"] = "Confiance",
        ["card.comp.one"] = "{0} composant",
        ["card.comp.many"] = "{0} composants",
        ["card.tbl.one"] = "{0} table sur {1}",
        ["card.tbl.many"] = "{0} tables sur {1}",
        ["card.manual"] = "⚑ Réparation manuelle",
        ["card.steps"] = "Voir les étapes →",
        ["side.criticals"] = "RÉSULTATS CRITIQUES",
        ["side.components"] = "SANTÉ DES COMPOSANTS",
        ["side.notes"] = "REMARQUES",
        ["side.comp.note"] = "Un composant qu'aucune table n'utilise n'est jamais compté comme un problème. Rien n'est déduit d'une lecture qui a échoué : dans ce cas Pincab Toolbox se tait.",
        ["comp.name.main-exe"] = "Visual Pinball X",
        ["comp.name.vpinmame"] = "VPinMAME",
        ["comp.name.vpinmame64"] = "VPinMAME 64-bit",
        ["comp.name.dmddevice"] = "dmddevice",
        ["comp.name.dmddevice64"] = "dmddevice 64-bit",
        ["comp.name.b2s"] = "B2S Backglass Server",
        ["comp.name.flexdmd"] = "FlexDMD",
        ["comp.name.popper"] = "PinUP Popper",
        ["comp.meta.absent"] = "absent",
        ["comp.meta.dbread"] = "base lue",
        ["comp.meta.dbunreadable"] = "base illisible",
        ["comp.st.ok"] = "✓ OK",
        ["comp.st.critical"] = "✕ Critique",
        ["comp.st.warn"] = "▲ Avertissement",
        ["comp.st.note"] = "✎ À noter",
        ["comp.code.BITNESS_DMD64_MISSING"] = "▲ 64-bit absent",
        ["comp.code.B2S_SERVER_MISSING"] = "▲ Manquant",
        ["comp.code.FLEXDMD_MISSING"] = "▲ Manquant",
        ["comp.code.VPINMAME_NOT_REGISTERED"] = "✕ Non enregistré",
        ["tbl.header"] = "TABLES ANALYSÉES",
        ["tbl.h.table"] = "Table",
        ["tbl.h.rom"] = "ROM",
        ["tbl.h.b2s"] = "Backglass",
        ["tbl.h.frontend"] = "Frontend",
        ["tbl.rom.ok"] = "✓ {0}",
        ["tbl.rom.missing"] = "✕ {0} absente",
        ["tbl.rom.notrequired"] = "✓ aucune requise",
        ["tbl.rom.unzipped"] = "▲ décompressée",
        ["tbl.b2s.present"] = "✓ présent",
        ["tbl.b2s.missing"] = "absent",
        ["tbl.fe.registered"] = "✓ enregistrée",
        ["tbl.fe.notregistered"] = "non enregistrée",
        ["tbl.unknown"] = "—",
        ["repaircard.none.title"] = "Aucune réparation automatique disponible sur ce scan",
        ["repaircard.none.body"] = "Repair sait corriger 4 types de problèmes aujourd'hui (fichier bloqué par Windows, ROM décompressée, média orphelin, processus d'affichage bloqué). Aucun n'est présent ici : les causes ci-dessus demandent d'installer ou d'enregistrer un composant, ce qu'un outil ne doit pas faire à ta place sans que tu voies exactement quoi.",
        ["repaircard.some.title"] = "Réparation automatique disponible",
        ["repaircard.open"] = "Ouvrir Repair",
        ["sys.needscan"] = "Lance un scan pour remplir cet onglet.",
        ["sys.scan.header"] = "DERNIER SCAN",
        ["sys.machine.header"] = "MACHINE",
        ["sys.root"] = "Racine analysée",
        ["sys.dirs"] = "Dossiers résolus",
        ["sys.os"] = "Système",
        ["sys.cpu"] = "Processeur",
        ["sys.cores"] = "{0} cœurs logiques",
        ["sys.ram"] = "Mémoire",
        ["sys.ram.fmt"] = "{0} Go disponibles",
        ["sys.screens"] = "Écrans",
        ["sys.screens.fmt"] = "{0} écran(s) — bureau virtuel {1} × {2}",
        ["more.tables"] = "+{0} autres — onglet Tables",
        ["more.results"] = "+{0} autres — onglet Tous les résultats",
    };

    private static readonly Dictionary<string, string> Es = new()
    {
        ["app.title"] = "Pincab Toolbox",
        ["tab.scanner"] = "Escáner",
        ["tab.diff"] = "Diff de scripts",
        ["tab.about"] = "Acerca de",
        ["tab.repair"] = "Repair",
        ["scan.root"] = "Carpeta raíz del pincab:",
        ["scan.browse"] = "Examinar…",
        ["scan.demo"] = "Modo demo",
        ["scan.start"] = "ESCANEAR MI PINCAB",
        ["scan.running"] = "Escaneando…",
        ["scan.cancel"] = "Cancelar",
        ["scan.export"] = "Exportar informe",
        ["scan.copyforum"] = "Copiar para el foro",
        ["report.copied"] = "Informe copiado — pégalo en el foro.",
        ["scan.placeholder"] = "Selecciona la carpeta raíz de tu instalación de pinball virtual (la que contiene Tables, VPinMAME, PinUPSystem…) y pulsa Escanear.",
        ["scan.empty"] = "Todavía no hay resultados.",
        ["scan.hint.notables"] = "No se encontraron tablas .vpx — comprueba que elegiste la carpeta correcta.",
        ["filter.critical"] = "Críticos",
        ["filter.warning"] = "Avisos",
        ["filter.note"] = "Notas",
        ["filter.info"] = "Info",
        ["filter.ok"] = "OK",
        ["score.a"] = "Instalación sana",
        ["score.b"] = "Algunos puntos a vigilar",
        ["score.c"] = "Instalación a corregir",
        ["score.f"] = "Instalación en mal estado",
        ["diagnosis.conf.high"] = "alta",
        ["diagnosis.conf.mid"] = "media",
        ["diagnosis.conf.low"] = "baja",
        ["hero.ok"] = "No se encontró ningún problema bloqueante",
        ["hero.blocking.one"] = "1 problema bloqueante impide que una tabla arranque",
        ["hero.blocking.many"] = "{0} problemas bloqueantes impiden que las tablas arranquen",
        ["priority.label"] = "CORREGIR ESTO PRIMERO",
        ["priority.watch"] = "MERECE UNA MIRADA",
        ["diagnosis.label"] = "DIAGNÓSTICO PRINCIPAL",
        ["diagnosis.confidence"] = "fiabilidad",
        ["priority.basedon"] = "Basado en:",
        ["detail.impact"] = "IMPACTO",
        ["detail.cause"] = "CAUSA PROBABLE",
        ["detail.fix"] = "CORRECCIÓN RECOMENDADA",
        ["detail.symptom"] = "LO QUE NOTARÁS",
        ["detail.explanation"] = "PARA ENTENDERLO MEJOR",
        ["detail.verify"] = "CÓMO VERIFICARLO",
        ["repair.checks.fixable"] = "✓ Reparable automáticamente",
        ["repair.checks.backup"] = "✓ Copia de seguridad antes del cambio",
        ["repair.checks.reversible"] = "✓ Reversible — deshacer en un clic",
        ["repair.checks.duration.seconds"] = "⏱ Unos segundos",
        ["repair.checks.duration.underminute"] = "⏱ Menos de un minuto",
        ["repair.checks.duration.minutes"] = "⏱ Unos minutos",
        ["repair.tag"] = "→ Ve a la pestaña Repair para aplicar esta corrección",
        ["repair.summary"] = "Repair podría corregir {0} de los {1} resultados aquí automáticamente — ve a la pestaña Repair.",
        ["repair.notautomatable"] = "Algunos pasos siempre quedarán manuales, con licencia o sin ella:",
        ["repair.goto"] = "Ir a la pestaña Repair →",
        ["repair.intro"] = "Repair puede corregir automáticamente algunos de los resultados anteriores: cada cambio se respalda antes de aplicarse y puede deshacerse, y nunca se aplica nada sin tu confirmación explícita, elemento por elemento. Introduce tu clave de licencia, construye el plan, revísalo y luego elige qué aplicar.",
        ["repair.license.label"] = "Clave de licencia",
        ["repair.license.hint"] = "Pega la clave que recibiste tras la compra.",
        ["repair.license.verify"] = "Verificar",
        ["repair.license.valid"] = "✓ Licencia válida.",
        ["repair.license.invalid"] = "Clave de licencia ausente o inválida — Repair solo mostrará lo que podría corregirse, sin aplicarlo.",
        ["repair.forceddryrun.banner"] = "⚠ MODO SIMULACIÓN — PINCAB_REPAIR_FORCE_DRYRUN está activo. Apply informará lo que habría hecho, pero no cambiará nada en el disco.",
        ["repair.forceddryrun.applied"] = "Solo simulación — no se escribió nada en el disco.",
        ["repair.plan.build"] = "Analizar qué se puede reparar",
        ["repair.plan.status"] = "{0} elemento(s) reparable(s), {1} paso(s) manual(es) por hacer tú mismo. Revisa la lista de abajo.",
        ["repair.plan.empty"] = "No hay nada que aplicar ahora mismo — o todo va bien, o cada corrección necesita una licencia, o los pasos restantes siguen siendo manuales.",
        ["repair.needscan"] = "Ejecuta primero un escaneo desde la pestaña Escáner.",
        ["repair.noneselected"] = "No hay nada seleccionado — marca al menos un elemento antes de aplicar.",
        ["repair.manual.label"] = "Manual — Repair no puede corregir esto automáticamente",
        ["repair.manual.noreason"] = "Todavía no existe una corrección automática para esto — consulta la propia indicación del resultado en el informe del Escáner.",
        ["repair.locked.label"] = "Existe una corrección — se necesita una licencia válida para verla y aplicarla.",
        ["repair.reversible.yes"] = "Reversible",
        ["repair.reversible.no"] = "No se puede deshacer",
        ["repair.backup.yes"] = "Con copia de seguridad previa",
        ["repair.backup.no"] = "Sin copia de seguridad (nada que restaurar)",
        ["repair.confirm.title"] = "Esto no se puede deshacer",
        ["repair.confirm.nonreversible"] = "Al menos una corrección seleccionada no se podrá deshacer una vez aplicada. ¿Quieres continuar?",
        ["repair.apply.button"] = "Aplicar correcciones seleccionadas",
        ["repair.apply.running"] = "Aplicando…",
        ["repair.apply.status"] = "{0} aplicado(s), {1} fallido(s).",
        ["repair.apply.recovery"] = "Algo salió mal al deshacer un cambio parcial — se conserva una copia de seguridad aquí, restáurala a mano si hace falta:",
        ["repair.done.label"] = "Reparado",
        ["repair.done.empty"] = "Todavía no se aplicó ninguna corrección.",
        ["repair.done.count"] = "{0} — {1} corrección(es) aplicada(s)",
        ["repair.done.partiallyundone"] = "{0} de ellas ya deshechas — el resto sigue en pie.",
        ["repair.done.fullyundone"] = "Deshecho por completo.",
        ["repair.undone.label"] = "Deshecho",
        ["repair.undone.empty"] = "Ningún plan deshecho todavía.",
        ["repair.undo.button"] = "Deshacer",
        ["repair.undo.ok"] = "Deshecho.",
        ["repair.undo.fail"] = "No se pudo deshacer por completo:",
        ["repair.undo.journalwarning"] = "⚠ La última escritura en el diario de deshacer falló — Undo podría estar incompleto para la acción más reciente.",
        ["col.severity"] = "Gravedad",
        ["col.category"] = "Módulo",
        ["col.subject"] = "Sujeto",
        ["col.message"] = "Detalles",
        ["col.action"] = "Acción",
        ["search.hint"] = "Buscar…",
        ["action.folder"] = "Abrir carpeta",
        ["action.update"] = "Abrir actualización",
        ["action.copy"] = "Copiar detalles",
        ["action.copied"] = "Copiado al portapapeles.",
        ["sev.Critical"] = "CRÍTICO",
        ["sev.Warning"] = "Aviso",
        ["sev.Note"] = "Nota",
        ["sev.Info"] = "Info",
        ["sev.Ok"] = "OK",
        ["diff.old"] = "Tabla antigua (.vpx o .vbs):",
        ["diff.new"] = "Tabla nueva (.vpx o .vbs):",
        ["diff.compare"] = "Comparar scripts",
        ["diff.summary"] = "{0} modificadas · {1} añadidas · {2} eliminadas",
        ["diff.placeholder"] = "Elige dos versiones de una tabla (o dos scripts .vbs) para ver exactamente qué cambió — antes de instalar una actualización a ciegas.",
        ["report.saved"] = "Informe guardado: ",
        ["status.ready"] = "Listo.",
        ["status.done"] = "Análisis completo · {0} comprobaciones — {1} críticos, {2} avisos, {3} info, {4} notas.",
        ["scan.demolabel"] = "Demo — instalación de ejemplo",
        ["diff.empty"] = "Compara el script de dos versiones de una tabla (.vpx o .vbs) para ver exactamente qué cambió. Elige un archivo antiguo y uno nuevo arriba, luego Comparar.",
        ["scan.copied"] = "✓ Copiado",
        ["cat.rom"] = "ROM",
        ["cat.bitness"] = "32/64 bits",
        ["cat.completeness"] = "Instalación",
        ["cat.compat"] = "Compatibilidad",
        ["cat.updates"] = "Actualizaciones",
        ["cat.security"] = "Seguridad",
        ["cat.dependencies"] = "Plugins",
        ["cat.aliasloop"] = "VPMAlias",
        ["cat.nvram"] = "NVRAM",
        ["cat.altcolor"] = "AltColor",
        ["cat.altsound"] = "AltSound",
        ["cat.screentopology"] = "Topología de pantallas",
        ["cat.junctions"] = "Uniones",
        ["cat.directb2s"] = "DirectB2S",
        ["cat.popperplaylist"] = "Playlists",
        ["cat.legacy"] = "Tablas antiguas",
        ["cat.disk"] = "Espacio en disco",
        ["cat.process"] = "PinUP Display",
        ["cat.display"] = "Configuración de pantallas",
        ["cat.media-orphan"] = "Medios huérfanos",
        ["cat.vpxversion"] = "Versión VPX",
        ["cat.com"] = "Registro COM",
        ["cat.chain-bitness"] = "Cadena 32/64 bits",
        ["cat.dmd-config"] = "Configuración DMD",
        ["cat.feature-enabled"] = "Función activada",
        ["cat.screenres-format"] = "Formato ScreenRes",
        ["cat.nvram-writable"] = "Escritura NVRAM",
        ["cat.audio-state"] = "Audio",
        ["cat.config-phantom"] = "Configuración duplicada",
        ["cat.dmd-com-port"] = "Puerto COM del DMD",
        ["cat.dpi-scaling"] = "Escala de pantalla",
        ["cat.locale-separator"] = "Separador decimal",
        ["about.tagline"] = "El mecánico de tu pincab.",
        ["about.body"] = "Pincab Toolbox escanea tu instalación de Visual Pinball X / PinUP Popper y te dice qué está roto, falta o no coincide — antes de que pulses Iniciar en una tabla.\n\n• Escaneo 100% local — tu cab, tus archivos y tus resultados nunca se suben, sin telemetría, sin cuenta.\n• Solo lectura — el escáner gratuito nunca modifica un solo archivo.\n• El Update Watcher usa la base de datos de código abierto Virtual Pinball Spreadsheet y solo te enlaza a páginas oficiales. Nunca descarga tablas, ROMs ni medios.\n• La única excepción: el botón \"Buscar actualizaciones\" de abajo es manual y opcional — lo pulsas tú, y contacta con GitHub solo para ver si existe una versión más reciente. Nada sobre tu cab, tus tablas o tus resultados de escaneo se envía nunca. Nunca se ejecuta por su cuenta.",
        ["about.version"] = "Versión",
        ["about.checkupdate"] = "Buscar actualizaciones",
        ["about.update.checking"] = "Comprobando…",
        ["about.update.uptodate"] = "Estás al día ({0}).",
        ["about.update.available"] = "Nueva versión {0} disponible — haz clic para abrir la página de la release.",
        ["about.update.error"] = "No se pudo comprobar (sin conexión, o GitHub inaccesible). Inténtalo más tarde.",
        ["onb.title"] = "Bienvenido a Pincab Toolbox",
        ["onb.lead"] = "Un chequeo rápido para tu gabinete de pinball virtual. Cerca de un minuto, y totalmente seguro.",
        ["onb.p1"] = "✓  Solo lectura — nunca modifica un solo archivo.",
        ["onb.p2"] = "✓  100 % local — nada se sube, sin cuenta, sin telemetría.",
        ["onb.p3"] = "✓  Encuentra lo que está roto, falta o no coincide — y explica cómo corregirlo.",
        ["onb.start"] = "Empezar",
        ["hero.causes.one"] = "Los resultados se reducen a 1 causa de fondo — corrige la causa, no cada síntoma uno por uno.",
        ["hero.causes.many"] = "Los resultados se reducen a {0} causas de fondo — corrige las causas, no cada síntoma uno por uno.",
        ["meta.mode"] = "Modo",
        ["meta.mode.demo"] = "Demostración",
        ["meta.mode.folder"] = "Carpeta",
        ["meta.started"] = "Iniciado",
        ["meta.duration"] = "Duración",
        ["meta.checks"] = "Controles",
        ["meta.tablecount"] = "Tablas analizadas",
        ["stab.causes"] = "Causas raíz",
        ["stab.results"] = "Todos los resultados",
        ["stab.components"] = "Componentes",
        ["stab.tables"] = "Tablas",
        ["stab.system"] = "Sistema",
        ["card.conf"] = "Confianza",
        ["card.comp.one"] = "{0} componente",
        ["card.comp.many"] = "{0} componentes",
        ["card.tbl.one"] = "{0} tabla de {1}",
        ["card.tbl.many"] = "{0} tablas de {1}",
        ["card.manual"] = "⚑ Corrección manual",
        ["card.steps"] = "Ver los pasos →",
        ["side.criticals"] = "RESULTADOS CRÍTICOS",
        ["side.components"] = "SALUD DE LOS COMPONENTES",
        ["side.notes"] = "NOTAS",
        ["side.comp.note"] = "Un componente que ninguna tabla usa nunca se cuenta como un problema. Nada se deduce de una lectura fallida: en ese caso Pincab Toolbox se queda callado.",
        ["comp.name.main-exe"] = "Visual Pinball X",
        ["comp.name.vpinmame"] = "VPinMAME",
        ["comp.name.vpinmame64"] = "VPinMAME 64 bits",
        ["comp.name.dmddevice"] = "dmddevice",
        ["comp.name.dmddevice64"] = "dmddevice 64 bits",
        ["comp.name.b2s"] = "B2S Backglass Server",
        ["comp.name.flexdmd"] = "FlexDMD",
        ["comp.name.popper"] = "PinUP Popper",
        ["comp.meta.absent"] = "ausente",
        ["comp.meta.dbread"] = "base leída",
        ["comp.meta.dbunreadable"] = "base ilegible",
        ["comp.st.ok"] = "✓ OK",
        ["comp.st.critical"] = "✕ Crítico",
        ["comp.st.warn"] = "▲ Aviso",
        ["comp.st.note"] = "✎ Nota",
        ["comp.code.BITNESS_DMD64_MISSING"] = "▲ Falta 64 bits",
        ["comp.code.B2S_SERVER_MISSING"] = "▲ Falta",
        ["comp.code.FLEXDMD_MISSING"] = "▲ Falta",
        ["comp.code.VPINMAME_NOT_REGISTERED"] = "✕ No registrado",
        ["tbl.header"] = "TABLAS ANALIZADAS",
        ["tbl.h.table"] = "Tabla",
        ["tbl.h.rom"] = "ROM",
        ["tbl.h.b2s"] = "Backglass",
        ["tbl.h.frontend"] = "Frontend",
        ["tbl.rom.ok"] = "✓ {0}",
        ["tbl.rom.missing"] = "✕ falta {0}",
        ["tbl.rom.notrequired"] = "✓ ninguna requerida",
        ["tbl.rom.unzipped"] = "▲ descomprimida",
        ["tbl.b2s.present"] = "✓ presente",
        ["tbl.b2s.missing"] = "ausente",
        ["tbl.fe.registered"] = "✓ registrada",
        ["tbl.fe.notregistered"] = "no registrada",
        ["tbl.unknown"] = "—",
        ["repaircard.none.title"] = "No hay reparación automática disponible en este escaneo",
        ["repaircard.none.body"] = "Repair hoy sabe corregir 4 tipos de problemas (archivo bloqueado por Windows, ROM descomprimida, medio huérfano, proceso de pantalla atascado). Ninguno está presente aquí: las causas de arriba requieren instalar o registrar un componente, algo que una herramienta no debe hacer en tu lugar sin que veas exactamente qué.",
        ["repaircard.some.title"] = "Reparación automática disponible",
        ["repaircard.open"] = "Abrir Repair",
        ["sys.needscan"] = "Ejecuta un escaneo para rellenar esta pestaña.",
        ["sys.scan.header"] = "ÚLTIMO ESCANEO",
        ["sys.machine.header"] = "MÁQUINA",
        ["sys.root"] = "Raíz analizada",
        ["sys.dirs"] = "Carpetas resueltas",
        ["sys.os"] = "Sistema",
        ["sys.cpu"] = "Procesador",
        ["sys.cores"] = "{0} núcleos lógicos",
        ["sys.ram"] = "Memoria",
        ["sys.ram.fmt"] = "{0} GB disponibles",
        ["sys.screens"] = "Pantallas",
        ["sys.screens.fmt"] = "{0} pantalla(s) — escritorio virtual {1} × {2}",
        ["more.tables"] = "+{0} más — pestaña Tablas",
        ["more.results"] = "+{0} más — pestaña Todos los resultados",
    };

    /// <summary>French templates per finding code ({0}, {1}… map to Finding.Args).</summary>
    private static readonly Dictionary<string, string> FrFindings = new()
    {
        // Ligne de regroupement (ScanReport.Rolled) — {0} = nombre, {1} = code regroupé.
        // FIELD-LOG 2026-08-13 : nommer les formats .txt/.pdf/.json explicitement (au lieu d'un
        // vague « rapport texte complet ») — un utilisateur terrain a exporté en HTML (le choix
        // par défaut du dialogue) sur la foi d'une réponse leur disant que tous les formats sont
        // complets, ce qui était faux pour HTML/MD/BBCode.
        ["GROUPED"] = "{0} résultats similaires ({1}) — regroupés pour garder la liste lisible. Exporte en .txt, .pdf ou .json pour les voir tous individuellement.",
        // Tier A (handoff Sonnet 5, 06/08) — B1. {0} = nom de la ROM.
        ["ALTCOLOR_INCOMPLETE"] = "« {0} » a un jeu de colorisation AltColor/Serum incomplet — des fichiers existent dans altcolor/{0}/ mais ne forment pas une paire complète (.vni+.pal, ou un fichier Serum+.pal). Le DMD risque de s'afficher en mono, ou la colorisation peut ne pas se charger du tout.",
        // Tier A (handoff Sonnet 5, 06/08) — B2. {0}=ROM, {1}=nb absents, {2}=nb total référencés.
        ["ALTSOUND_SAMPLE_MISSING"] = "« {0} » : altsound.csv référence {1} échantillon(s) sur {2} qui sont absents de altsound/{0}/ — ces sons resteront silencieux, ou le plugin AltSound peut échouer à se charger.",
        // Tier A (handoff Sonnet 5, 06/08) — C1. {0} = fichier ScreenRes concerné (ScreenRes.txt ou "TableName").
        ["DISPLAY_OFFSCREEN"] = "La position du backglass définie dans « {0} » tombe entièrement en dehors de tous les écrans connectés — elle ne sera jamais visible, même si le fichier se charge sans erreur.",
        // Tier A (handoff Sonnet 5, 06/08) — G3. {0} = chemin du dossier, {1} = cible de la jonction.
        ["BROKEN_JUNCTION"] = "« {0} » est une jonction/lien symbolique pointant vers « {1} », qui n'existe plus — tout ce qui est attendu sous ce dossier est invisible pour Visual Pinball, PinUP Popper et ce scan.",
        // Tier A (handoff Sonnet 5, 06/08) — H2. {0} = nom du fichier .directb2s.
        ["B2S_MALFORMED"] = "« {0} » n'est pas du XML bien formé — B2S Backglass Server refuse de le charger, ce backglass n'apparaîtra donc pas du tout.",
        // Tier A (handoff Sonnet 5, 06/08) — F1. {0} = nb de jeux affectés, {1} = exemples (noms ou GameID).
        ["POPPER_ORPHAN_PLAYLIST"] = "{0} jeu(x) dans la base PinUP Popper sont affectés à une playlist qui n'existe plus — ceci est connu pour figer le menu du frontend Popper à l'ouverture.",
        // Tier A (handoff Sonnet 5, 06/08) — H1. {0} = nom de la ROM (sans extension).
        ["NVRAM_EMPTY"] = "Le fichier de sauvegarde NVRAM de « {0} » est vide (0 octet) — VPinMAME ne peut lire aucun état sauvegardé, la table risque de démarrer sur un écran noir ou de figer.",
        // Tier A (handoff Sonnet 5, 06/08) — E1. {0} = chaîne de la boucle (ex. "a -> b -> a").
        ["VPMALIAS_LOOP"] = "VPMAlias.txt contient une boucle d'alias : {0}. VPinMAME plante (stack overflow) dès qu'une table a besoin de ce nom de ROM.",

        ["ROM_MISSING"] = "« {0} » ne démarrera pas : la ROM « {1} » est absente du dossier roms.",
        ["ROM_OK"] = "« {0} » — ROM trouvée : {1}.",
        ["ROM_NOT_REQUIRED"] = "« {0} » ne nécessite pas de ROM (table originale/EM).",
        ["ROM_UNZIPPED"] = "La ROM de « {0} » est présente sous forme de dossier décompressé « {1} » — VPinMAME charge les ROMs depuis des .zip, elle ne sera donc pas trouvée.",
        ["POPPER_MEDIA_MISSING"] = "{0} jeu(x) enregistré(s) sur {1} n'ont pas d'image de wheel sous POPMedia — ils apparaîtront vides dans la roue PinUP Popper.",
        ["SCRIPT_UNREADABLE"] = "Impossible de lire le script de « {0} » ({1}).",
        ["TABLES_DIR_NOT_FOUND"] = "Aucun dossier de tables trouvé sous la racine choisie — est-ce bien une installation Visual Pinball ?",
        ["ROMS_DIR_NOT_FOUND"] = "Dossier roms de VPinMAME introuvable — vérification des ROMs ignorée.",
        ["BLOCKED_DLL"] = "« {0} » est bloqué par Windows (fichier téléchargé) — il risque de ne pas se charger tant que tu ne l'as pas débloqué.",
        ["BLOCKED_NONE"] = "Aucun fichier bloqué par Windows détecté.",
        ["BITNESS_INVENTORY"] = "{0} — {1} ({2}).",
        ["BITNESS_NOTHING_FOUND"] = "Aucun binaire connu à analyser.",
        ["BITNESS_MISMATCH_VPM"] = "Un Visual Pinball 64-bit est installé mais seul un VPinMAME.dll 32-bit a été trouvé. Le VPX 64-bit ne peut pas utiliser le serveur COM 32-bit — les tables à ROM échoueront.",
        ["BITNESS_MISMATCH_VPM32"] = "Un Visual Pinball 32-bit est installé mais seul un VPinMAME.dll 64-bit a été trouvé. Le VPX 32-bit ne peut pas utiliser le serveur COM 64-bit — les tables à ROM échoueront.",
        ["B2S_SERVER_MISSING"] = "Aucun B2SBackglassServer.dll trouvé sous cette installation alors que des backglass (ou des scripts) en ont besoin — les backglass ne s'afficheront pas tant que le B2S Backglass Server n'est pas installé et enregistré.",
        ["FLEXDMD_MISSING"] = "{0} table(s) utilisent FlexDMD mais aucun FlexDMD.dll n'a été trouvé sous cette installation — leur affichage DMD/score ne fonctionnera pas tant que FlexDMD n'est pas installé et enregistré.",
        ["B2S_SERVER_OK"] = "B2S Backglass Server installé et fichiers backglass présents.",
        ["BITNESS_HYBRID_INSTALL"] = "Des exécutables Visual Pinball 32-bit ET 64-bit sont présents. Une installation hybride fonctionne, mais chaque plugin (dmddevice, B2S, FlexDMD) doit exister dans LES DEUX variantes — ce scan liste ce que tu as.",
        ["BITNESS_DMD64_MISSING"] = "VPX 64-bit détecté mais pas de dmddevice64.dll — les DMD externes ne fonctionneront pas depuis le VPinMAME 64-bit.",
        ["B2S_MISSING"] = "« {0} » n'a pas de fichier backglass .directb2s à côté de la table.",
        ["B2S_ORPHAN"] = "Le backglass « {0}.directb2s » ne correspond à aucune table — B2S charge les backglass par nom de base exact, celui-ci est donc ignoré.",
        ["POPPER_NOT_REGISTERED"] = "« {0} » n'est pas enregistrée dans PinUP Popper — elle n'apparaîtra pas dans le frontend.",
        ["POPPER_DB_NOT_FOUND"] = "Base PinUP Popper introuvable — vérifications frontend ignorées.",
        ["PUPPACK_PRESENT"] = "« {0} » a un PUP-Pack ({1}).",
        ["COMPAT_MIN_VERSION"] = "« {0} » déclare nécessiter VPX {1}+ — vérifie ta version installée avant de lancer.",
        // Rétroactif (comparateur VPX du 05/08, complété 06/08 — R1). {0}=table, {1}=version requise, {2}=version installée.
        ["VPX_VERSION_OUTDATED"] = "« {0} » déclare nécessiter Visual Pinball X {1}+, mais la version VPX la plus récente installée est {2} — cette table risque de ne pas se charger ou de mal fonctionner tant que Visual Pinball X n'est pas mis à jour.",
        ["COMPAT_SIGNATURE"] = "« {0} » : {1}.",
        ["UPDATE_AVAILABLE"] = "« {0} » — tu as la v{1}, la v{2} est répertoriée sur le Virtual Pinball Spreadsheet. Voir {3}.",
        ["VPS_UNAVAILABLE"] = "Base VPS indisponible (hors ligne ?) — vérification des mises à jour ignorée. Elle se fera à la prochaine connexion.",
        ["VPS_MATCH_SUMMARY"] = "Update Watcher : {0}/{1} tables reconnues dans la base VPS (heuristique, bêta). Mods/variantes non comparés : {2} (ils suivent leur propre versionnage).",
        ["SCANNER_ERROR"] = "Le module « {0} » a échoué : {1}.",
        ["LOW_DISK_SPACE"] = "Espace disque faible sur {0} : {1} Go libres. Visual Pinball peut échouer à charger les textures (« Unable to Create Offscreen Texture ») ou les médias quand le disque est presque plein.",
        ["VPT_LEGACY_PRESENT"] = "{0} table(s) .vpt (Visual Pinball 9, ancien format) présentes. Elles n'apparaissent souvent pas dans PinUP Popper car « .vpt » ne fait pas partie des extensions de l'émulateur VPX.",
        ["PINUP_DISPLAY_ZOMBIE"] = "PinUpDisplay.exe est toujours actif alors qu'aucune table n'est en cours — un reste d'une session précédente. Peut bloquer le lancement de la prochaine table tant qu'il n'est pas fermé.",
        ["DISPLAY_SETUP_INCOMPLETE"] = "Cette installation attend une configuration multi-écrans (un composant backglass ou DMD est présent) mais seul {0} écran est actuellement connecté. Si ton cab tourne normalement avec plus d'écrans, ils sont peut-être en veille, débranchés, ou reconnectés dans le mauvais ordre.",
        ["ORPHANED_MEDIA_FILE"] = "{0} fichier(s) média dans les dossiers de PinUP Popper ne correspondent à aucune table installée — probablement des restes de tables supprimées ou renommées.",
        // ── Tier B (handoff Sonnet 5, 06/08) — tous Severity.Note (ADR-010 Doctrine).
        // {0} = nom du périphérique de lecture par défaut.
        ["AUDIO_DEFAULT_SUSPECT"] = "Le périphérique de lecture Windows par défaut est actuellement « {0} » — son nom suggère une sortie audio écran/HDMI plutôt que des enceintes dédiées. C'est un point connu où Windows réinitialise silencieusement le défaut au démarrage ; vérifie que c'est bien voulu.",
        // {0} = pourcentage d'échelle (ex. "125", sans le signe %, déjà ajouté dans le gabarit).
        ["DPI_SCALING_NONSTANDARD"] = "La mise à l'échelle d'affichage Windows pour cet utilisateur est réglée à {0} % au lieu de 100 %. C'est une cause connue de fenêtre backglass ou table qui s'affiche tronquée ou décalée sur certains cabs — vérifie ton affichage si tu remarques ça.",
        // {0} = section du pilote (pin2dmd/zedmd/pindmd3), {1} = port COM configuré.
        ["DMD_COM_PORT_NOT_FOUND"] = "dmddevice.ini active « {0} » sur {1}, mais Windows ne liste pas {1} comme actif actuellement. Si ce DMD est connecté et sous tension, ce cas est connu pour causer un gel de plusieurs secondes au lancement, le temps que le pilote l'attende.",
        // {0} = séparateur décimal détecté (ex. ",").
        ["LOCALE_DECIMAL_SEPARATOR"] = "Le séparateur décimal de cet utilisateur Windows est « {0} » au lieu de « . ». Certains scripts de table VPX et analyses de physique/configuration supposent un point, et peuvent mal se comporter avec un séparateur virgule — un point de friction connu pour les installations Windows en français.",
        // Pas d'argument — le constat ne dépend d'aucune valeur variable.
        ["VPINMAME_CONFIG_PHANTOM"] = "Une configuration VPinMAME dans le registre (HKCU\\Software\\Freeware\\Visual PinMame) ET un fichier VPinMAME.ini ont été trouvés. VPinMAME peut être configuré via l'un ou l'autre — si tu modifies l'un sans voir les changements s'appliquer, tu modifies peut-être celui qui n'est pas actuellement utilisé.",

        // ── Lot communauté 10/08 — LOT A (COM Registration Health). {0} = ProgID.
        ["COM_NOT_REGISTERED"] = "« {0} » n'est enregistré dans aucune des deux vues du registre COM (32 et 64-bit), alors que le composant correspondant est présent dans cette installation et qu'au moins une table en a besoin — ça va échouer avec une erreur du type « ActiveX component can't create object » ou « Library not registered (Exception from HRESULT: 0x8002801D) ».",
        // {0} = ProgID, {1} = chemin enregistré.
        ["COM_STALE_PATH"] = "« {0} » est enregistré mais pointe vers « {1} », qui n'existe plus — un reste d'enregistrement d'une installation précédente. Le chargement échouera.",
        ["COM_PATH_OUTSIDE_INSTALL"] = "« {0} » est enregistré, mais vers une copie en dehors de cette installation (« {1} ») — cette installation a aussi sa propre copie du composant. Les tables lancées ici chargeront en réalité la copie enregistrée (l'autre).",
        ["COM_OK"] = "« {0} » est enregistré et pointe à l'intérieur de cette installation.",
        // {0} = ProgID, {1} = architecture manquante ("32-bit"/"64-bit").
        ["COM_BITNESS_GAP"] = "Un Visual Pinball {1} est installé mais « {0} » n'est enregistré que dans l'AUTRE architecture — le processus {1} ne peut pas l'utiliser. C'est le classique problème « le 32-bit et le 64-bit sont deux écosystèmes différents ».",
        // Pas d'argument — les 4 conditions sont déterministes, le constat ne dépend d'aucune valeur variable.
        ["VPINMAME_NOT_REGISTERED"] = "VPinMAME.dll est présent mais VPinMAME.Controller n'est enregistré dans aucune des deux vues du registre COM (32 ou 64-bit), alors qu'au moins une table en a besoin — toutes les tables à ROM vont échouer au démarrage (« ActiveX component can't create object » / « Library not registered »). C'est presque toujours causé par une installation VPX copiée à la main sans jamais avoir lancé le Setup.exe de VPinMAME.",

        // ── LOT B (Chain Bitness Doctor). {0} = nom du composant (B2S/FlexDMD), {1} = architecture ("32-bit"/"64-bit").
        ["CHAIN_BITNESS_GAP"] = "Un Visual Pinball {1} est installé et au moins une table a besoin de {0}, mais aucun binaire {0} en {1} n'a été trouvé sous cette installation — le chargement échouera depuis le processus {1}.",

        // ── LOT C (dmddevice.ini Config Doctor). Pas d'argument.
        ["DMD_VIRTUAL_DISABLED"] = "dmddevice.ini a le DMD virtuel désactivé (« [virtualdmd] enabled = false »), et aucun pilote de DMD matériel n'est activé non plus dans le même fichier. Si tu n'as pas de DMD physique, ton DMD va simplement disparaître sans message d'erreur — une mise à jour de Freezy est connue pour réinitialiser cette valeur toute seule.",
        // {0}=left, {1}=top, {2}=width, {3}=height.
        ["DMD_POSITION_OFFSCREEN"] = "dmddevice.ini positionne le DMD virtuel à ({0},{1}) avec une taille de {2}x{3}, ce qui tombe entièrement en dehors de tous les écrans connectés — il ne sera jamais visible, même si dmddevice.ini se charge sans erreur.",

        // ── LOT D (Feature Enabled Doctor). {0} = nom de la ROM.
        ["ALTSOUND_PRESENT_NOT_ENABLED"] = "« {0} » a un pack AltSound installé sous altsound/{0}/, mais le mode Alt Sound de VPinMAME est réglé sur 0 (désactivé) pour cette ROM — le pack est présent mais silencieux.",
        ["ALTCOLOR_PRESENT_NOT_ENABLED"] = "« {0} » a un jeu de colorisation AltColor/Serum complet installé sous altcolor/{0}/, mais la colorisation DMD de VPinMAME est désactivée pour cette ROM — le DMD s'affichera en mono.",

        // ── LOT F (ScreenRes.txt Format Honesty). {0} = nom du fichier concerné (ScreenRes.txt ou nom de table).
        ["SCREENRES_UNPARSED"] = "« {0} » est présent mais pas dans un format que cet outil sait vérifier (pas de marqueur « # V2 », ou une structure non reconnue) — sa position de backglass/DMD n'est pas vérifiée ; ceci n'est pas une affirmation qu'il y a un problème.",

        // ── LOT G (NVRAM Folder Writability). Pas d'argument.
        ["NVRAM_FOLDER_NOT_WRITABLE"] = "Le dossier nvram de VPinMAME existe mais un vrai test d'écriture a échoué — les meilleurs scores et réglages par table vont échouer à s'enregistrer silencieusement, table après table, sans aucune erreur affichée.",
    };

    /// <summary>Spanish templates per finding code ({0}, {1}… map to Finding.Args).</summary>
    private static readonly Dictionary<string, string> EsFindings = new()
    {
        ["GROUPED"] = "{0} resultados similares ({1}) — agrupados para mantener la lista legible. Exporta en .txt, .pdf o .json para verlos todos individualmente.",
        ["ALTCOLOR_INCOMPLETE"] = "« {0} » tiene un set de colorización AltColor/Serum incompleto — hay archivos en altcolor/{0}/ pero no forman un par completo (.vni+.pal, o un archivo Serum+.pal). El DMD puede mostrarse en mono, o la colorización puede no cargar en absoluto.",
        ["ALTSOUND_SAMPLE_MISSING"] = "« {0} »: altsound.csv referencia {1} muestra(s) de {2} que faltan en altsound/{0}/ — estos sonidos quedarán en silencio, o el plugin AltSound puede fallar al cargar.",
        ["DISPLAY_OFFSCREEN"] = "La posición del backglass definida en « {0} » cae por completo fuera de todas las pantallas conectadas — nunca será visible, aunque el archivo cargue sin error.",
        ["BROKEN_JUNCTION"] = "« {0} » es una unión/enlace simbólico que apunta a « {1} », que ya no existe — todo lo esperado bajo esta carpeta es invisible para Visual Pinball, PinUP Popper y este escaneo.",
        ["B2S_MALFORMED"] = "« {0} » no es XML bien formado — B2S Backglass Server se niega a cargarlo, así que este backglass no aparecerá en absoluto.",
        ["POPPER_ORPHAN_PLAYLIST"] = "{0} juego(s) en la base de PinUP Popper están asignados a una playlist que ya no existe — esto es conocido por congelar el menú del frontend Popper al abrirlo.",
        ["NVRAM_EMPTY"] = "El archivo de guardado NVRAM de « {0} » está vacío (0 bytes) — VPinMAME no puede leer ningún estado guardado, la tabla puede arrancar en pantalla negra o quedarse colgada.",
        ["VPMALIAS_LOOP"] = "VPMAlias.txt contiene un bucle de alias: {0}. VPinMAME se cae (desbordamiento de pila) en cuanto una tabla necesita este nombre de ROM.",
        ["ROM_MISSING"] = "« {0} » no arrancará: la ROM « {1} » no está en la carpeta roms.",
        ["ROM_OK"] = "« {0} » — ROM encontrada: {1}.",
        ["ROM_NOT_REQUIRED"] = "« {0} » no necesita ROM (tabla original/EM).",
        ["ROM_UNZIPPED"] = "La ROM de « {0} » está presente como carpeta descomprimida « {1} » — VPinMAME carga las ROMs desde .zip, así que no se encontrará.",
        ["POPPER_MEDIA_MISSING"] = "{0} juego(s) registrado(s) de {1} no tienen imagen de wheel en POPMedia — aparecerán vacíos en la rueda de PinUP Popper.",
        ["SCRIPT_UNREADABLE"] = "No se pudo leer el script de « {0} » ({1}).",
        ["TABLES_DIR_NOT_FOUND"] = "No se encontró ninguna carpeta de tablas bajo la raíz elegida — ¿es realmente una instalación de Visual Pinball?",
        ["ROMS_DIR_NOT_FOUND"] = "No se encontró la carpeta roms de VPinMAME — se omitió la verificación de ROMs.",
        ["BLOCKED_DLL"] = "« {0} » está bloqueado por Windows (archivo descargado) — puede que no cargue mientras no lo desbloquees.",
        ["BLOCKED_NONE"] = "No se detectó ningún archivo bloqueado por Windows.",
        ["BITNESS_INVENTORY"] = "{0} — {1} ({2}).",
        ["BITNESS_NOTHING_FOUND"] = "No hay ningún binario conocido que analizar.",
        ["BITNESS_MISMATCH_VPM"] = "Hay instalado un Visual Pinball de 64 bits pero solo se encontró un VPinMAME.dll de 32 bits. El VPX de 64 bits no puede usar el servidor COM de 32 bits — las tablas con ROM fallarán.",
        ["BITNESS_MISMATCH_VPM32"] = "Hay instalado un Visual Pinball de 32 bits pero solo se encontró un VPinMAME.dll de 64 bits. El VPX de 32 bits no puede usar el servidor COM de 64 bits — las tablas con ROM fallarán.",
        ["B2S_SERVER_MISSING"] = "No se encontró B2SBackglassServer.dll bajo esta instalación aunque hay backglass (o scripts) que lo necesitan — los backglass no se mostrarán mientras B2S Backglass Server no esté instalado y registrado.",
        ["FLEXDMD_MISSING"] = "{0} tabla(s) usan FlexDMD pero no se encontró ningún FlexDMD.dll bajo esta instalación — su pantalla de DMD/puntuación no funcionará mientras FlexDMD no esté instalado y registrado.",
        ["B2S_SERVER_OK"] = "B2S Backglass Server instalado y archivos de backglass presentes.",
        ["BITNESS_HYBRID_INSTALL"] = "Hay ejecutables de Visual Pinball de 32 bits Y de 64 bits presentes. Una instalación híbrida funciona, pero cada plugin (dmddevice, B2S, FlexDMD) debe existir en AMBAS variantes — este escaneo lista lo que tienes.",
        ["BITNESS_DMD64_MISSING"] = "VPX de 64 bits detectado pero no hay dmddevice64.dll — los DMD externos no funcionarán desde el VPinMAME de 64 bits.",
        ["B2S_MISSING"] = "« {0} » no tiene archivo de backglass .directb2s junto a la tabla.",
        ["B2S_ORPHAN"] = "El backglass « {0}.directb2s » no corresponde a ninguna tabla — B2S carga los backglass por nombre base exacto, así que este se ignora.",
        ["POPPER_NOT_REGISTERED"] = "« {0} » no está registrada en PinUP Popper — no aparecerá en el frontend.",
        ["POPPER_DB_NOT_FOUND"] = "No se encontró la base de datos de PinUP Popper — se omitieron las comprobaciones de frontend.",
        ["PUPPACK_PRESENT"] = "« {0} » tiene un PUP-Pack ({1}).",
        ["COMPAT_MIN_VERSION"] = "« {0} » declara necesitar VPX {1}+ — comprueba tu versión instalada antes de lanzarla.",
        ["VPX_VERSION_OUTDATED"] = "« {0} » declara necesitar Visual Pinball X {1}+, pero la versión de VPX más reciente instalada es {2} — esta tabla puede fallar al cargar o funcionar mal mientras Visual Pinball X no se actualice.",
        ["COMPAT_SIGNATURE"] = "« {0} »: {1}.",
        ["UPDATE_AVAILABLE"] = "« {0} » — tienes la v{1}, la v{2} está listada en el Virtual Pinball Spreadsheet. Ver {3}.",
        ["VPS_UNAVAILABLE"] = "Base VPS no disponible (¿sin conexión?) — se omitió la comprobación de actualizaciones. Se hará en la próxima conexión.",
        ["VPS_MATCH_SUMMARY"] = "Update Watcher: {0}/{1} tablas reconocidas en la base VPS (heurística, beta). Mods/variantes no comparados: {2} (siguen su propio versionado).",
        ["SCANNER_ERROR"] = "El módulo « {0} » falló: {1}.",
        ["LOW_DISK_SPACE"] = "Poco espacio en disco en {0}: {1} GB libres. Visual Pinball puede fallar al cargar texturas (« Unable to Create Offscreen Texture ») o medios cuando el disco está casi lleno.",
        ["VPT_LEGACY_PRESENT"] = "{0} tabla(s) .vpt (Visual Pinball 9, formato antiguo) presentes. A menudo no aparecen en PinUP Popper porque « .vpt » no forma parte de las extensiones del emulador VPX.",
        ["PINUP_DISPLAY_ZOMBIE"] = "PinUpDisplay.exe sigue activo aunque no hay ninguna tabla en curso — un resto de una sesión anterior. Puede bloquear el lanzamiento de la siguiente tabla mientras no se cierre.",
        ["DISPLAY_SETUP_INCOMPLETE"] = "Esta instalación espera una configuración multipantalla (hay un componente de backglass o DMD presente) pero solo hay {0} pantalla conectada actualmente. Si tu cab suele funcionar con más pantallas, puede que estén en reposo, desconectadas, o reconectadas en el orden incorrecto.",
        ["ORPHANED_MEDIA_FILE"] = "{0} archivo(s) de medios en las carpetas de PinUP Popper no corresponden a ninguna tabla instalada — probablemente restos de tablas eliminadas o renombradas.",
        ["AUDIO_DEFAULT_SUSPECT"] = "El dispositivo de reproducción predeterminado de Windows es actualmente « {0} » — su nombre sugiere una salida de audio de pantalla/HDMI en lugar de altavoces dedicados. Es un punto conocido donde Windows reinicia en silencio el predeterminado al arrancar; comprueba que sea realmente lo que quieres.",
        ["DPI_SCALING_NONSTANDARD"] = "La escala de pantalla de Windows para este usuario está en {0} % en lugar de 100 %. Es una causa conocida de que la ventana del backglass o de la tabla se muestre recortada o desplazada en algunos cabs — revisa tu pantalla si notas esto.",
        ["DMD_COM_PORT_NOT_FOUND"] = "dmddevice.ini activa « {0} » en {1}, pero Windows no lista {1} como activo actualmente. Si este DMD está conectado y encendido, este caso es conocido por causar un congelamiento de varios segundos al iniciar, mientras el controlador lo espera.",
        ["LOCALE_DECIMAL_SEPARATOR"] = "El separador decimal de este usuario de Windows es « {0} » en lugar de « . ». Algunos scripts de tabla VPX y análisis de física/configuración asumen un punto, y pueden comportarse mal con un separador de coma — un punto de fricción conocido para instalaciones de Windows en francés.",
        ["VPINMAME_CONFIG_PHANTOM"] = "Se encontró una configuración de VPinMAME en el registro (HKCU\\Software\\Freeware\\Visual PinMame) Y un archivo VPinMAME.ini. VPinMAME puede configurarse desde cualquiera de los dos — si modificas uno y no ves que los cambios se apliquen, puede que estés modificando el que no se está usando actualmente.",
        ["COM_NOT_REGISTERED"] = "« {0} » no está registrado en ninguna de las dos vistas del registro COM (32 y 64 bits), aunque el componente correspondiente está presente en esta instalación y al menos una tabla lo necesita — esto fallará con un error del tipo « ActiveX component can't create object » o « Library not registered (Exception from HRESULT: 0x8002801D) ».",
        ["COM_STALE_PATH"] = "« {0} » está registrado pero apunta a « {1} », que ya no existe — un resto de registro de una instalación anterior. La carga fallará.",
        ["COM_PATH_OUTSIDE_INSTALL"] = "« {0} » está registrado, pero hacia una copia fuera de esta instalación (« {1} ») — esta instalación también tiene su propia copia del componente. Las tablas lanzadas aquí en realidad cargarán la copia registrada (la otra).",
        ["COM_OK"] = "« {0} » está registrado y apunta dentro de esta instalación.",
        ["COM_BITNESS_GAP"] = "Hay instalado un Visual Pinball {1} pero « {0} » solo está registrado en la OTRA arquitectura — el proceso {1} no puede usarlo. Es el clásico problema de « 32 bits y 64 bits son dos ecosistemas diferentes ».",
        ["VPINMAME_NOT_REGISTERED"] = "VPinMAME.dll está presente pero VPinMAME.Controller no está registrado en ninguna de las dos vistas del registro COM (32 o 64 bits), aunque al menos una tabla lo necesita — todas las tablas con ROM fallarán al arrancar (« ActiveX component can't create object » / « Library not registered »). Casi siempre lo causa una instalación de VPX copiada a mano sin haber ejecutado nunca el Setup.exe de VPinMAME.",
        ["CHAIN_BITNESS_GAP"] = "Hay instalado un Visual Pinball {1} y al menos una tabla necesita {0}, pero no se encontró ningún binario {0} en {1} bajo esta instalación — la carga fallará desde el proceso {1}.",
        ["DMD_VIRTUAL_DISABLED"] = "dmddevice.ini tiene el DMD virtual desactivado (« [virtualdmd] enabled = false »), y tampoco hay ningún controlador de DMD físico activado en el mismo archivo. Si no tienes un DMD físico, tu DMD simplemente desaparecerá sin mensaje de error — se sabe que una actualización de Freezy reinicia este valor por sí sola.",
        ["DMD_POSITION_OFFSCREEN"] = "dmddevice.ini coloca el DMD virtual en ({0},{1}) con un tamaño de {2}x{3}, lo cual cae por completo fuera de todas las pantallas conectadas — nunca será visible, aunque dmddevice.ini cargue sin error.",
        ["ALTSOUND_PRESENT_NOT_ENABLED"] = "« {0} » tiene un pack AltSound instalado en altsound/{0}/, pero el modo Alt Sound de VPinMAME está en 0 (desactivado) para esta ROM — el pack está presente pero silencioso.",
        ["ALTCOLOR_PRESENT_NOT_ENABLED"] = "« {0} » tiene un set de colorización AltColor/Serum completo instalado en altcolor/{0}/, pero la colorización DMD de VPinMAME está desactivada para esta ROM — el DMD se mostrará en mono.",
        ["SCREENRES_UNPARSED"] = "« {0} » está presente pero no en un formato que esta herramienta sepa verificar (sin marcador « # V2 », o una estructura no reconocida) — su posición de backglass/DMD no se verifica; esto no es una afirmación de que haya un problema.",
        ["NVRAM_FOLDER_NOT_WRITABLE"] = "La carpeta nvram de VPinMAME existe pero una prueba de escritura real falló — los mejores puntajes y ajustes por tabla fallarán al guardarse en silencio, tabla tras tabla, sin que se muestre ningún error.",
    };

    /// <summary>French fix hints per finding code (English fallback is in the Core Finding.FixHint).</summary>
    private static readonly Dictionary<string, string> FrFixHints = new()
    {
        ["BITNESS_MISMATCH_VPM"] = "Installe et enregistre le VPinMAME 64-bit (VPinMAME64.dll) pour le VPX 64-bit, ou lance le VPX 32-bit pour ces tables.",
        ["BITNESS_MISMATCH_VPM32"] = "Installe et enregistre le VPinMAME 32-bit (VPinMAME.dll) pour le VPX 32-bit, ou lance le VPX 64-bit pour ces tables.",
        ["B2S_SERVER_MISSING"] = "Installe le B2S Backglass Server (il enregistre B2SBackglassServer.dll), garde-le dans ton dossier Tables et enregistre-le en administrateur.",
        ["FLEXDMD_MISSING"] = "Télécharge FlexDMD, place FlexDMD.dll dans ton dossier Visual Pinball et enregistre-le (regsvr32 en administrateur).",
        ["BITNESS_DMD64_MISSING"] = "Télécharge le dmddevice64.dll 64-bit depuis les releases open source de Freezy dmd-extensions et place-le à côté de VPinMAME64.",
        ["BLOCKED_DLL"] = "Clic droit sur le fichier → Propriétés → coche « Débloquer » → OK. Ou en PowerShell : Unblock-File « <chemin> »",
        ["B2S_MISSING"] = "Si tu utilises un écran backglass, télécharge le .directb2s correspondant et place-le dans le dossier des tables avec exactement le même nom de base.",
        ["B2S_ORPHAN"] = "Si ce backglass appartient à une table, renomme-le avec le nom de base exact de la table (identique au .vpx). Sinon, c'est un reste que tu peux supprimer.",
        // Audit 2026-08-04 : manquait — ROM_MISSING est le Critical le plus fréquent (8 occurrences
        // sur le propre scan réel de Maxime), c'était donc le message de fix le plus vu qui
        // retombait silencieusement en anglais pour un utilisateur FR.
        ["ALTCOLOR_INCOMPLETE"] = "Retélécharge le jeu de colorisation de cette ROM et extrais tous les fichiers qu'il contient dans le dossier altcolor correspondant — une extraction partielle (par ex. seulement le .pal, ou seulement le .vni) est la cause la plus fréquente.",
        ["ALTSOUND_SAMPLE_MISSING"] = "Réextrais le pack AltSound de cette ROM dans le dossier altsound correspondant — une extraction partielle est la cause la plus fréquente. Si tu as modifié altsound.csv à la main, vérifie la colonne FNAME par rapport aux fichiers réellement présents.",
        ["DISPLAY_OFFSCREEN"] = "Relance B2S_ScreenResIdentifier (ou ton éditeur ScreenRes) avec tous les écrans branchés dans leur disposition normale du cab, puis resauvegarde — un ScreenRes.txt/.res périmé après un changement d'écran ou de carte graphique en est la cause la plus fréquente.",
        ["BROKEN_JUNCTION"] = "Reconnecte le disque/partage vers lequel pointe le lien, ou recrée la jonction (mklink /J) vers son emplacement correct et actuellement disponible. Supprime-la si le dossier lié a disparu pour de bon.",
        ["B2S_MALFORMED"] = "Retélécharge ou réexporte ce backglass — un téléchargement tronqué ou un export interrompu en est la cause la plus fréquente.",
        ["POPPER_ORPHAN_PLAYLIST"] = "Dans l'outil d'administration de PinUP Popper, rouvre et resauvegarde l'affectation de playlist de chaque jeu concerné (ou retire-la), ou recrée la playlist manquante.",
        ["NVRAM_EMPTY"] = "Supprime le fichier .nv vide et lance la table une fois — VPinMAME le recrée avec les valeurs par défaut. Si tu as une sauvegarde .nv d'avant le problème, restaure-la plutôt pour garder tes meilleurs scores.",
        ["VPMALIAS_LOOP"] = "Ouvre VPMAlias.txt et casse la boucle : le dernier alias de la chaîne doit pointer directement vers le vrai nom de set ROM, pas vers un alias déjà vu.",
        ["ROM_MISSING"] = "Place le fichier .zip de la ROM (nom exact, sans le décompresser) dans le dossier roms de VPinMAME.",
        ["ROM_UNZIPPED"] = "Recompresse le dossier de la ROM en un .zip du même nom dans le dossier roms (ne zippe pas un dossier parent supplémentaire autour).",
        ["POPPER_MEDIA_MISSING"] = "Ajoute une image de wheel nommée exactement comme le jeu (son GameName Popper) sous POPMedia\\<émulateur>\\Wheel, ou relance l'import des médias Popper.",
        ["LOW_DISK_SPACE"] = "Libère de l'espace sur ce disque (anciennes sauvegardes, tables/médias inutilisés) — garde au moins quelques Go de marge.",
        ["VPT_LEGACY_PRESENT"] = "N'ajoute pas « .vpt » à l'émulateur VPX existant — l'auteur de PinUP (NailBuster) le déconseille, ça casse le lancement des .vpt. Crée plutôt une entrée d'émulateur legacy VP9 dédiée.",
        ["PINUP_DISPLAY_ZOMBIE"] = "Ferme PinUpDisplay.exe depuis le Gestionnaire des tâches avant de relancer une table.",
        ["DISPLAY_SETUP_INCOMPLETE"] = "Vérifie le câblage et que la veille des moniteurs est désactivée indépendamment de la veille du PC — cause très fréquente d'écrans qui se reconnectent dans le mauvais ordre après un redémarrage (guides communautaires : Pincab Passion « Changer l'ordre des écrans dans Windows »).",
        ["ORPHANED_MEDIA_FILE"] = "Peut être revu à la main, ou mis en quarantaine avec Repair une fois disponible (déplacé de côté avec sauvegarde, jamais supprimé). Ne supprime pas de média à la main sans vérifier d'abord — des variantes comme « (SCREEN2) »/« (SCREEN3) » peuvent encore être utilisées même si le nom de base semble inconnu.",
        // Rétroactif (comparateur VPX du 05/08, complété 06/08 — R1). Pas de {n} : les deux numéros de
        // version sont déjà dans le message ci-dessus, inutile de les répéter ici.
        ["VPX_VERSION_OUTDATED"] = "Mets à jour Visual Pinball X vers la version requise par la table (indiquée dans le message ci-dessus). Tu peux garder ta version actuelle en parallèle — les builds VPX coexistent, les autres tables ne sont pas affectées.",
        // Tier B (handoff Sonnet 5, 06/08).
        ["AUDIO_DEFAULT_SUSPECT"] = "Si ce n'est pas la sortie audio que tu veux, redéfinis le périphérique de lecture par défaut sur tes enceintes dans les paramètres Son de Windows.",
        ["DPI_SCALING_NONSTANDARD"] = "Dans les paramètres d'affichage Windows, remets « Échelle » à 100 % pour les écrans du cab, ou vérifie que Visual Pinball / B2S tournent en mode compatible DPI si tu gardes une échelle supérieure à 100 %.",
        ["DMD_COM_PORT_NOT_FOUND"] = "Vérifie que le DMD est sous tension et que sa connexion USB/série est branchée, ou mets à jour dmddevice.ini si le port COM a changé.",
        ["LOCALE_DECIMAL_SEPARATOR"] = "Dans les paramètres régionaux Windows, tu peux régler le « symbole décimal » sur « . » dans le format de nombre avancé — certains propriétaires de pincab font tourner leur compte cab en format numérique anglais (États-Unis) spécifiquement pour éviter ce genre de souci.",
        ["VPINMAME_CONFIG_PHANTOM"] = "Si tu t'appuies sur VPinMAME.ini, vérifie que ses réglages s'appliquent réellement ; sinon, envisage de le supprimer pour éviter l'ambiguïté et garder le registre comme source unique.",

        // ── Lot communauté 10/08 — LOT A→G.
        ["COM_NOT_REGISTERED"] = "Lance l'outil d'enregistrement du composant (son Setup.exe / son application d'enregistrement / regsvr32) en tant qu'administrateur.",
        ["COM_STALE_PATH"] = "Relance l'outil d'enregistrement du composant depuis son emplacement ACTUEL pour écraser l'enregistrement périmé.",
        ["COM_PATH_OUTSIDE_INSTALL"] = "Si tu voulais utiliser la copie de CETTE installation, relance son outil d'enregistrement depuis ici.",
        ["COM_BITNESS_GAP"] = "Enregistre la version du composant qui correspond à l'architecture manquante, ou lance la version de VPX dont l'architecture EST déjà enregistrée.",
        ["VPINMAME_NOT_REGISTERED"] = "Lance le Setup.exe de VPinMAME (dans le dossier VPinMAME) en tant qu'administrateur — il enregistre le composant COM. C'est le correctif le plus courant pour « aucune table à ROM ne démarre ».",
        ["CHAIN_BITNESS_GAP"] = "Installe la version manquante du composant dans l'architecture concernée, à côté du Visual Pinball correspondant.",
        ["DMD_VIRTUAL_DISABLED"] = "Si tu n'as pas de DMD physique, mets « enabled = true » sous [virtualdmd] dans dmddevice.ini.",
        ["DMD_POSITION_OFFSCREEN"] = "Réinitialise les valeurs left/top/width/height de [virtualdmd] dans dmddevice.ini (ou supprime-les pour revenir aux valeurs par défaut) avec tous les écrans branchés dans leur disposition normale du cab.",
        ["ALTSOUND_PRESENT_NOT_ENABLED"] = "Dans les options par jeu de VPinMAME (menu F1, ou l'interface de configuration VPinMAME), change le mode son de 0/Original pour utiliser le pack AltSound installé.",
        ["ALTCOLOR_PRESENT_NOT_ENABLED"] = "Dans les options par jeu de VPinMAME, active la colorisation DMD (« Colorize DMD » / couleurs DMD externes) pour utiliser le jeu installé.",
        ["SCREENRES_UNPARSED"] = "Si la position de ton backglass semble fausse, relance B2S_ScreenResIdentifier (ou ton éditeur ScreenRes) pour régénérer le fichier dans le format actuel.",
        ["NVRAM_FOLDER_NOT_WRITABLE"] = "Vérifie que le dossier nvram n'est pas en lecture seule et que ton compte utilisateur Windows a le droit d'écriture dessus (clic droit → Propriétés → Sécurité).",
    };

    /// <summary>Spanish fix hints per finding code (English fallback is in the Core Finding.FixHint).</summary>
    private static readonly Dictionary<string, string> EsFixHints = new()
    {
        ["BITNESS_MISMATCH_VPM"] = "Instala y registra el VPinMAME de 64 bits (VPinMAME64.dll) para el VPX de 64 bits, o ejecuta el VPX de 32 bits para estas tablas.",
        ["BITNESS_MISMATCH_VPM32"] = "Instala y registra el VPinMAME de 32 bits (VPinMAME.dll) para el VPX de 32 bits, o ejecuta el VPX de 64 bits para estas tablas.",
        ["B2S_SERVER_MISSING"] = "Instala el B2S Backglass Server (registra B2SBackglassServer.dll), consérvalo en tu carpeta Tables y regístralo como administrador.",
        ["FLEXDMD_MISSING"] = "Descarga FlexDMD, coloca FlexDMD.dll en tu carpeta de Visual Pinball y regístralo (regsvr32 como administrador).",
        ["BITNESS_DMD64_MISSING"] = "Descarga el dmddevice64.dll de 64 bits desde las releases de código abierto de Freezy dmd-extensions y colócalo junto a VPinMAME64.",
        ["BLOCKED_DLL"] = "Clic derecho sobre el archivo → Propiedades → marca « Desbloquear » → Aceptar. O en PowerShell: Unblock-File « <ruta> »",
        ["B2S_MISSING"] = "Si usas una pantalla de backglass, descarga el .directb2s correspondiente y colócalo en la carpeta de tablas con exactamente el mismo nombre base.",
        ["B2S_ORPHAN"] = "Si este backglass pertenece a una tabla, renómbralo con el nombre base exacto de la tabla (idéntico al .vpx). Si no, es un resto que puedes eliminar.",
        ["ALTCOLOR_INCOMPLETE"] = "Vuelve a descargar el set de colorización de esta ROM y extrae todos los archivos que contiene en la carpeta altcolor correspondiente — una extracción parcial (por ejemplo solo el .pal, o solo el .vni) es la causa más frecuente.",
        ["ALTSOUND_SAMPLE_MISSING"] = "Vuelve a extraer el pack AltSound de esta ROM en la carpeta altsound correspondiente — una extracción parcial es la causa más frecuente. Si modificaste altsound.csv a mano, comprueba la columna FNAME contra los archivos realmente presentes.",
        ["DISPLAY_OFFSCREEN"] = "Vuelve a ejecutar B2S_ScreenResIdentifier (o tu editor de ScreenRes) con todas las pantallas conectadas en su disposición normal del cab, y vuelve a guardar — un ScreenRes.txt/.res obsoleto tras un cambio de pantalla o de tarjeta gráfica es la causa más frecuente.",
        ["BROKEN_JUNCTION"] = "Reconecta el disco/recurso compartido al que apunta el enlace, o recrea la unión (mklink /J) hacia su ubicación correcta y actualmente disponible. Elimínala si la carpeta enlazada desapareció definitivamente.",
        ["B2S_MALFORMED"] = "Vuelve a descargar o reexportar este backglass — una descarga truncada o una exportación interrumpida es la causa más frecuente.",
        ["POPPER_ORPHAN_PLAYLIST"] = "En la herramienta de administración de PinUP Popper, vuelve a abrir y guardar la asignación de playlist de cada juego afectado (o quítala), o recrea la playlist que falta.",
        ["NVRAM_EMPTY"] = "Elimina el archivo .nv vacío y lanza la tabla una vez — VPinMAME lo recrea con los valores por defecto. Si tienes una copia de seguridad .nv anterior al problema, restáurala en su lugar para conservar tus mejores puntajes.",
        ["VPMALIAS_LOOP"] = "Abre VPMAlias.txt y rompe el bucle: el último alias de la cadena debe apuntar directamente al nombre real del set de ROM, no a un alias ya visto.",
        ["ROM_MISSING"] = "Coloca el archivo .zip de la ROM (nombre exacto, sin descomprimirlo) en la carpeta roms de VPinMAME.",
        ["ROM_UNZIPPED"] = "Vuelve a comprimir la carpeta de la ROM en un .zip con el mismo nombre dentro de la carpeta roms (no la comprimas dentro de una carpeta superior adicional).",
        ["POPPER_MEDIA_MISSING"] = "Añade una imagen de wheel con el nombre exacto del juego (su GameName de Popper) en POPMedia\\<emulador>\\Wheel, o vuelve a ejecutar la importación de medios de Popper.",
        ["LOW_DISK_SPACE"] = "Libera espacio en este disco (copias de seguridad antiguas, tablas/medios sin usar) — mantén al menos unos GB de margen.",
        ["VPT_LEGACY_PRESENT"] = "No añadas « .vpt » al emulador VPX existente — el autor de PinUP (NailBuster) lo desaconseja, rompe el lanzamiento de los .vpt. Crea mejor una entrada de emulador legacy VP9 dedicada.",
        ["PINUP_DISPLAY_ZOMBIE"] = "Cierra PinUpDisplay.exe desde el Administrador de tareas antes de volver a lanzar una tabla.",
        ["DISPLAY_SETUP_INCOMPLETE"] = "Revisa el cableado y que el reposo de los monitores esté desactivado independientemente del reposo del PC — causa muy frecuente de pantallas que se reconectan en el orden incorrecto tras un reinicio (guías de la comunidad: Pincab Passion « Changer l'ordre des écrans dans Windows »).",
        ["ORPHANED_MEDIA_FILE"] = "Puede revisarse a mano, o ponerse en cuarentena con Repair cuando esté disponible (movido a un lado con copia de seguridad, nunca eliminado). No elimines medios a mano sin comprobar antes — variantes como « (SCREEN2) »/« (SCREEN3) » todavía pueden estar en uso aunque el nombre base parezca desconocido.",
        ["VPX_VERSION_OUTDATED"] = "Actualiza Visual Pinball X a la versión requerida por la tabla (indicada en el mensaje de arriba). Puedes mantener tu versión actual en paralelo — los builds de VPX coexisten, las demás tablas no se ven afectadas.",
        ["AUDIO_DEFAULT_SUSPECT"] = "Si esta no es la salida de audio que quieres, vuelve a configurar el dispositivo de reproducción predeterminado a tus altavoces en los ajustes de Sonido de Windows.",
        ["DPI_SCALING_NONSTANDARD"] = "En los ajustes de pantalla de Windows, vuelve a poner la « Escala » al 100 % para las pantallas del cab, o comprueba que Visual Pinball / B2S se ejecuten en modo compatible con DPI si mantienes una escala superior al 100 %.",
        ["DMD_COM_PORT_NOT_FOUND"] = "Comprueba que el DMD esté encendido y que su conexión USB/serie esté conectada, o actualiza dmddevice.ini si el puerto COM cambió.",
        ["LOCALE_DECIMAL_SEPARATOR"] = "En la configuración regional de Windows, puedes poner el « símbolo decimal » en « . » dentro del formato de número avanzado — algunos propietarios de pincab configuran su cuenta del cab en formato numérico inglés (Estados Unidos) específicamente para evitar este tipo de problema.",
        ["VPINMAME_CONFIG_PHANTOM"] = "Si dependes de VPinMAME.ini, comprueba que sus ajustes realmente se apliquen; si no, considera eliminarlo para evitar la ambigüedad y mantener el registro como fuente única.",
        ["COM_NOT_REGISTERED"] = "Ejecuta la herramienta de registro del componente (su Setup.exe / su aplicación de registro / regsvr32) como administrador.",
        ["COM_STALE_PATH"] = "Vuelve a ejecutar la herramienta de registro del componente desde su ubicación ACTUAL para sobrescribir el registro obsoleto.",
        ["COM_PATH_OUTSIDE_INSTALL"] = "Si querías usar la copia de ESTA instalación, vuelve a ejecutar su herramienta de registro desde aquí.",
        ["COM_BITNESS_GAP"] = "Registra la versión del componente que corresponde a la arquitectura que falta, o ejecuta la versión de VPX cuya arquitectura YA está registrada.",
        ["VPINMAME_NOT_REGISTERED"] = "Ejecuta el Setup.exe de VPinMAME (en la carpeta VPinMAME) como administrador — registra el componente COM. Es la corrección más habitual para « ninguna tabla con ROM arranca ».",
        ["CHAIN_BITNESS_GAP"] = "Instala la versión que falta del componente en la arquitectura afectada, junto al Visual Pinball correspondiente.",
        ["DMD_VIRTUAL_DISABLED"] = "Si no tienes un DMD físico, pon « enabled = true » bajo [virtualdmd] en dmddevice.ini.",
        ["DMD_POSITION_OFFSCREEN"] = "Reinicia los valores left/top/width/height de [virtualdmd] en dmddevice.ini (o elimínalos para volver a los valores por defecto) con todas las pantallas conectadas en su disposición normal del cab.",
        ["ALTSOUND_PRESENT_NOT_ENABLED"] = "En las opciones por juego de VPinMAME (menú F1, o la interfaz de configuración de VPinMAME), cambia el modo de sonido de 0/Original para usar el pack AltSound instalado.",
        ["ALTCOLOR_PRESENT_NOT_ENABLED"] = "En las opciones por juego de VPinMAME, activa la colorización DMD (« Colorize DMD » / colores DMD externos) para usar el set instalado.",
        ["SCREENRES_UNPARSED"] = "Si la posición de tu backglass parece incorrecta, vuelve a ejecutar B2S_ScreenResIdentifier (o tu editor de ScreenRes) para regenerar el archivo en el formato actual.",
        ["NVRAM_FOLDER_NOT_WRITABLE"] = "Comprueba que la carpeta nvram no esté en modo solo lectura y que tu cuenta de usuario de Windows tenga permiso de escritura sobre ella (clic derecho → Propiedades → Seguridad).",
    };
}
